; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; ----------------------- ESP32 Dev Board -----------------------
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
build_flags = -D PIO_ESP32_DEV_BOARD

monitor_port = /dev/tty.usbserial-0001
monitor_speed = 115200
upload_port = /dev/tty.usbserial-0001

; Convertor html to Cpp python 
extra_scripts = pre:extra_script.py
custom_in_html = src/FrameWeb.html
custom_out_h = src/FrameWeb.cpp

lib_deps = # Using a library name
   https://github.com/tzapu/WiFiManager.git#master
   https://github.com/Links2004/arduinoWebSockets#master
  DNSServer
  WebServer
  ArduinoJson

; ----------------------- Seeed Xiao ESP32S3 -----------------------
[env:xiao_esp32s3]
platform = espressif32 ; https://github.com/Seeed-Studio/platform-seeedboards.git
board =  seeed_xiao_esp32s3 ;seeed-xiao-esp32-s3-plus
framework = arduino
build_flags = -D PIO_SEEED_XIAO_ESP32S3_BOARD

monitor_port = /dev/tty.usbmodem14301 
monitor_speed = 115200
upload_port = /dev/tty.usbmodem14301 

; Convertor html to Cpp python 
extra_scripts = pre:extra_script.py
custom_in_html = src/FrameWeb.html
custom_out_h = src/FrameWeb.cpp

lib_deps = # Using a library name
   https://github.com/tzapu/WiFiManager.git#master
   https://github.com/Links2004/arduinoWebSockets#master
   DNSServer
   WebServer
   ArduinoJson

; ----------------------- Default Environment -----------------------
[platformio]
default_envs = esp32dev