; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; ----------------------- ESP32 Dev Board -----------------------
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
build_flags =  -D PIO_ESP32_DEV_BOARD 
;               -D LOG_FRAMEWEB_ENABLED ; Enable debug output for FrameWeb (prefix [F])

monitor_port = /dev/tty.usbserial-14210
monitor_speed = 115200
upload_port = /dev/tty.usbserial-14210

; Partition options:
board_build.partitions = default.csv    ; app ~1.3MB + OTA  77.1% (used 1010241 bytes from 1310720 bytes)
;board_build.partitions = no_ota.csv     ; larger single app, no OTA
;board_build.partitions = min_spiffs.csv ; app + small SPIFFS
;board_build.partitions = huge_app.csv     ; max app size, no OTA (active)

; HTML-to-C++ generator
extra_scripts = pre:extra_script.py
; Single-file example (full HTML)
; custom_in_html = src/FrameWeb.html
; custom_out_h = src/FrameWeb.cpp
;
; Lightweight example (~50% flash gain depending on pages)
; custom_in_html = src/FrameLight.html
; custom_out_h = src/FrameWeb.cpp
;
; Multi-file example (sequential mapping input[i] -> output[i])
; custom_in_html = src/FrameLight.html
;                  src/FrameWeb.html
; custom_out_h = src/FrameWeb.cpp
;                src/FrameOther.cpp
;
custom_in_html = src/FrameWeb.html
custom_out_h = src/FrameWeb.cpp
custom_out_zip = zib 

lib_deps = # Using a library name
   https://github.com/tzapu/WiFiManager.git#master
   https://github.com/Links2004/arduinoWebSockets#master
   DNSServer
   WebServer
   ArduinoJson

; ----------------------- Seeed Xiao ESP32S3 -----------------------
[env:xiao_esp32s3]
platform = espressif32 ; https://github.com/Seeed-Studio/platform-seeedboards.git
board =  seeed_xiao_esp32s3 ;seeed-xiao-esp32-s3-plus
framework = arduino
build_flags = -D PIO_SEEED_XIAO_ESP32S3_BOARD
              -D LOG_FRAMEWEB_ENABLED ; Enable debug output for FrameWeb (prefix [F])

monitor_port = /dev/tty.usbmodem14210 
monitor_speed = 115200
upload_port = /dev/tty.usbmodem14210 

; Partition options:
board_build.partitions = default.csv    ; app ~1.3MB + OTA  72.5% (used 949685 bytes from 1310720 bytes)
;board_build.partitions = no_ota.csv     ; larger single app, no OTA
;board_build.partitions = min_spiffs.csv ; app + small SPIFFS
;board_build.partitions = huge_app.csv     ; max app size, no OTA (active)

; HTML-to-C++ generator
extra_scripts = pre:extra_script.py
; Single-file example (full HTML)
; custom_in_html = src/FrameWeb.html
; custom_out_h = src/FrameWeb.cpp
;
; Lightweight example (~50% flash gain depending on pages)
; custom_in_html = src/FrameLight.html
; custom_out_h = src/FrameWeb.cpp
;
; Multi-file example (sequential mapping input[i] -> output[i])
; custom_in_html = src/FrameLight.html
;                  src/FrameWeb.html
; custom_out_h = src/FrameWeb.cpp
;                src/FrameOther.cpp
;
custom_in_html = src/FrameWeb.html
custom_out_h = src/FrameWeb.cpp
custom_out_zip = zib

lib_deps = # Using a library name
   https://github.com/tzapu/WiFiManager.git#master
   https://github.com/Links2004/arduinoWebSockets#master
   DNSServer
   WebServer
   ArduinoJson

; ----------------------- Seeed Xiao ESP32C6 -----------------------
[env:seeed_xiao_esp32c6]
platform = https://github.com/sgryphon/platform-espressif32.git#sgryphon/add-esp32-arduino-libs

platform_packages =
    platformio/framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#3.0.0-rc1
    platformio/framework-arduinoespressif32-libs @ https://github.com/espressif/esp32-arduino-libs.git#idf-release/v5.1
board = seeed_xiao_esp32c6
framework = arduino

build_flags = -D PIO_SEEED_XIAO_ESP32C6_BOARD
              -D LOG_FRAMEWEB_ENABLED ; Enable debug output for FrameWeb (prefix [F])

monitor_port = /dev/tty.usbmodem14210 
monitor_speed = 115200
upload_port = /dev/tty.usbmodem14210 

; Partition options:
; board_build.partitions = default.csv    ; 92.3% (used 1208600 bytes from 1310720 bytes)
;board_build.partitions = no_ota.csv     ; larger single app, no OTA
board_build.partitions = min_spiffs.csv ; app + small SPIFFS  61.5% (used 1208600 bytes from 1966080 bytes)
;board_build.partitions = huge_app.csv     ; max app size, no OTA (active)

; HTML-to-C++ generator
extra_scripts = pre:extra_script.py
; Single-file example (full HTML)
; custom_in_html = src/FrameWeb.html
; custom_out_h = src/FrameWeb.cpp
;
; Lightweight example (~50% flash gain depending on pages)
; custom_in_html = src/FrameLight.html
; custom_out_h = src/FrameWeb.cpp
;
; Multi-file example (sequential mapping input[i] -> output[i])
; custom_in_html = src/FrameLight.html
;                  src/FrameWeb.html
; custom_out_h = src/FrameWeb.cpp
;                src/FrameOther.cpp
;
custom_in_html = src/FrameWeb.html
custom_out_h = src/FrameWeb.cpp
custom_out_zip = zib

lib_deps = # Using a library name
   https://github.com/tzapu/WiFiManager.git#master
   https://github.com/Links2004/arduinoWebSockets#master
   DNSServer
   WebServer
   ArduinoJson

; ----------------------- Default Environment -----------------------
[platformio]
default_envs = esp32dev, xiao_esp32s3, seeed_xiao_esp32c6
; Frameworks: is teseted on Arduino framework, but can be used with ESP-IDF as well
; seeed_xiao_esp32c6, esp32dev, xiao_esp32s3 default environments used when -e is not specified