/*
  * @file FrameWeb.cpp
  * @brief Implementation of the ESP32 Web Framework
  * 
  * This file contains the complete implementation of the web system for ESP32,
  * including WiFi management, HTTP server, OTA and WebSocket handling.
  *
  * Generated HTML payload mode:
  * - Controlled by custom_out_zip in platformio.ini.
  * - custom_out_zip = plain keeps HTTP_* chunks as plain HTML.
  * - custom_out_zip = zip stores every chunk as FrameWeb zip payloads:
  *   "<raw_size>:<hex_zlib_payload>".
  * - custom_out_zip = zip_if_best stores, for each chunk, the smallest
  *   payload between plain HTML and FrameWeb zip format.
  *
  * Runtime decoding is automatic through decodeHtmlChunk().
*/

// Zip generation mode is controlled by platformio.ini custom_out_zip.
// LOG_FRAMEWEB_ENABLED enables FrameWeb debug output (prefix [F]).
#include "FrameWeb.h"
#include <rom/miniz.h>

// This block is auto-regenerated by extra_script.py at pre-build.
// Do not edit lines between the two markers below.

 
// ============ Pre-generated HTML (generated from FrameWeb.html) ============
// These character strings PROGMEM are stored in Flash to save RAM
//! Warning: The section between 'Start Generated' and 'End Generated' is auto-generated.
//! It is generated from src/FrameWeb.html. Any manual changes will be lost at the next generation.
//! To modify HTML content, edit src/FrameWeb.html and regenerate FrameWeb.cpp using extra_script.py.
//! See platformio.ini for the extra_script.py configuration used during the build process.
//! stats: len=stored string content size (inside quotes), source=original UTF-8 HTML size, payload=stored UTF-8 payload size (plain or size:HEX_ZLIB), gain=source-payload
//---- Start Generated from src/FrameLight.html file --- 2026-05-19 16:19:10
const char HTTP_HEADAL[] PROGMEM = "<!DOCTYPE html><head><meta charset='UTF-8'><meta name='viewport' content='width=device-width, initial-scale=1.0'><title>ESP32</title></head>";
//---- len : 140 bytes | source=140 | payload=140 | gain=0 (0.0%)
const char HTTP_BODYUP[] PROGMEM = "<body><div align='center'><header><h1>ESP32 Uploader</h1></header><p>Transfer a file to SPIFFS. Gzip supported.</p><div><div>File Upload</div><div><div><div>- Select a file to upload to the EFS.</div><div><form method='post' enctype='multipart/form-data'><input type='file' name='Choose file' accept='.gz,.html,.ico,.js,.json,.css,.png,.gif,.bmp,.jpg,.xml,.pdf,.htm'><button type='submit' name='submit'>Upload</button></form></div></div></div></div><div><button onclick=\"window.location='/';\">Back</button></div></div></body></html>";
//---- len : 534 bytes | source=532 | payload=532 | gain=0 (0.0%)
const char HTTP_BODYID[] PROGMEM = "782:78DA9592414FC3300C85FF8AB5CBE0402BE0485709A64E42420269837BD6B85B208DABC459B77F4F9A0C361008767113D57EEFF36B8B25C95D5948B501A1D5CA4CC6351A463B2E8B350A89363C2FCB6AFE747D0555BB442951C28248BB220F2F42D97775E5BD91B8CDD6DC6A68944630C4D0903712C800AF11246E548D599177D13095299946ADBC15AC42DB0C057B8B41FCB3E1502EE0CE52EF1044D06C85112B8C4E0E5432A866F3EC7872E9998328995AABFA6D32EA9591D4679AEAE83619E7B8ED34D9B0EECDA8ACF6E7224F73FF99D76E987C508E0F530920FFCEFEA2B08F94F5978D6354DE855405836361D977A7ED90F4B257476680991EAE7F323D878D85DC87C89442FCF8CAB3816CBE738CED69403EAA0E2C49FF38D25F41A4E0E01DFFB346D9B6171681366823935016CE1E17B7E7A7820CAA096438FD8C7154DF016691128E";
//---- len : 654 bytes | source=782 | payload=654 | gain=128 (16.4%)
const char HTTP_BODYI0[] PROGMEM = "673:78DA7551CB6AC33010FC95BD090A89A1BD0545104A720EF1A167D95E27023D8CB54EF1DF776539AEFBC845A0DD9D99DD19D998BB92E929C748E8E05093093ECA6269C8C12A698DDA80ACD40523E99E6451A91D5CB00A8122D00DE1589EDF5EB7B2E0C165B8D47784F7E05B73CD8054881091C8F82BE3021C4FE5165E7EC29246E8F1A1317D2234D8EAC1B29AF60D7F2C12175B633132C15F0624F83027B39020235361514FA81956A40B57075B5DA18536F47B51BB463067C97A3581863A38971668FBE0A6BBAD89B4639A045192310EF464E15E7421920087740BCDFC53326626D3646EF0DAE12C2343978070D776E09A0F1EB958E4EAEF6E9F8310DF89FC3F17D9F24D3D6520D68124D39F32236D3E4D6BC4CAC8ECD6F35D3823F1480ED6A345BE58C96A20620C8D5D5A6BA89CE1ED0F5D67470E69EAF17032F091C5F47E01B2DEE646";
//---- len : 652 bytes | source=673 | payload=652 | gain=21 (3.1%)
const char HTTP_BODYI1[] PROGMEM = "<div><p>* All parameters in config.json are affected.</p><p>** Login, password, and flags reset to default. EFS reformatted.</p><p>*** Device reboots in AP mode to select a new WiFi network.</p></div></div></body></html>";
//---- len : 220 bytes | source=220 | payload=220 | gain=0 (0.0%)
const char HTTP_FIRM0[] PROGMEM = "1401:78DA85546D4FDB3010FE2B071338DD2029F08DA691C6CBB44920D060DABE4D6E72692D12DB732E2D15F4BFEF9C975260B02F4EE27B9EE79E3B9F134F4CB64CE24CCD41166AAAC722454DE84412CF5066E8F879909CDF5C1F1DC217E5CA8574083F6C2609E38823BC7430DBA1AE6E3F43DE23EB0619C219E6B22E0872E34A49C7104E940EE3C83699DBE595FA3AD22CFBD0CAAFA5BD44AFBF09F629A0449A996C2CAEAF6E6E05C89494E1D23E08409DD2D2E258946C4759E928F2847D96910214536A5B1899FDF6BBDC04A56D4DD0527255A0174BD1D258F8FC02B42CD173BC0D864F6A22A33B7C554F4A4522E90B6A83DC32AF9D749E37D7F572EDCCD46155BDD86FFC59371589ED00C730DC794BC8263FA5D34A4F8FBBD63181B8E00A644D868F41A5B2289620733EEFA74EDA67225D4146A7854AEFC6DB0BA533B3080B93CAB6A791186D272732BDDBA86FC349953A652909F25A3787100CE0612E5D33083086CCA475C903174E91CE0BF4AF27CB6F59F0EC140623CFE84B7E8FE57B3318A91C82AD26C1E3236CF53C4EEC906AA7472B1F0B65969DCF9979A12A428D2EE8CF6B0FD6669149185A871ED8CD70D0DAF103C356342EE00BCB9DF167E075DBE8FDCC75C15F97175F89EC77FC5373FB99CCA1B0ADEE1F167AB3CF4CCC896DF8A2F82D2C504F69766A4A9E4B3929B0EBA7459FB001B0326610351F644816A35E3524BCA753C3F75B13A3C5D31409F804979266A133B5CE02AFF6110E86C301EF8B1D315AAD5AE3AF1DFB749B6E3BAB1ECCD3467505C9180E8743D8DD858DCD188EBCFAC3FFADB10B6F00B0A8F06D7C3BBE904BBEA3D97B7ED139E35E187E4B54232D8CBB839633EA348D451DB47F963D105177F7DB5885DC3D3F1A038F5E0DF8BCE3A8BB037C419A7F6D34A3B248FE023F81E571";
//---- len : 1321 bytes | source=1401 | payload=1321 | gain=80 (5.7%)
const char HTTP_EXPL0[] PROGMEM = "<script>function clic(pa, el) {var r = confirm('Are you sure you want to ' + pa + ' ' + el + ' ?');if (r == true) {window.location = '/explorer?cmd=' + pa + '&file=' + el;}}</script><body><div align='center'><header><h1>File Explorer</h1></header><p>Browse and manage files in the EFS.</p><div><div>Files</div><div>";
//---- len : 315 bytes | source=315 | payload=315 | gain=0 (0.0%)
const char HTTP_EXPL1[] PROGMEM = "<div><div><a href='##F##'>##F##</a><span> (##S##)</span></div><div><button onclick=\"clic('download', '##F##')\">Download</button><button onclick=\"clic('remove', '##F##')\">Remove</button></div></div>";
//---- len : 201 bytes | source=197 | payload=197 | gain=0 (0.0%)
//---- total len : 4037 bytes | source=4260 | payload=4031 | gain=229 (5.4%)
//---- End Generated

namespace {

// ===== Internal zip helper utilities (local to this translation unit) =====
// Purpose:
// - Convert compressed bytes to/from ASCII hex representation.
// - Detect whether a generated chunk is in FrameWeb zip format.

char nibbleToHex(uint8_t nibble) {
  return (nibble < 10) ? static_cast<char>('0' + nibble) : static_cast<char>('A' + (nibble - 10));
}

int hexToNibble(char ch) {
  if (ch >= '0' && ch <= '9') {
    return ch - '0';
  }
  if (ch >= 'a' && ch <= 'f') {
    return 10 + (ch - 'a');
  }
  if (ch >= 'A' && ch <= 'F') {
    return 10 + (ch - 'A');
  }
  return -1;
}

String bytesToHex(const uint8_t* data, size_t length) {
  String hex;
  if (!hex.reserve(length * 2)) {
    return String();
  }

  for (size_t index = 0; index < length; ++index) {
    const uint8_t value = data[index];
    hex += nibbleToHex((value >> 4) & 0x0F);
    hex += nibbleToHex(value & 0x0F);
  }

  return hex;
}

bool hexToBytes(const String& hex, uint8_t* output, size_t outputLength) {
  if ((hex.length() % 2) != 0 || (hex.length() / 2) != outputLength) {
    return false;
  }

  for (size_t index = 0; index < outputLength; ++index) {
    const int high = hexToNibble(hex[index * 2]);
    const int low = hexToNibble(hex[(index * 2) + 1]);
    if (high < 0 || low < 0) {
      return false;
    }
    output[index] = static_cast<uint8_t>((high << 4) | low);
  }

  return true;
}

bool isZippedString(const String& payload) {
  // Fast format detection for FrameWeb zip payloads:
  // "<raw_size>:<hex_zlib_payload>"
  // Current strategy validates only the numeric size prefix and ':' separator
  // to keep this check very cheap for all HTTP_* chunk reads.
  const int separator = payload.indexOf(':');
  if (separator <= 0) {
    return false;
  }

  for (int i = 0; i < separator; ++i) {
    const char ch = payload[i];
    if (ch < '0' || ch > '9') {
      return false;
    }
  }
  /*
  Optional strict validation (kept disabled for speed):
  - Enforces even hex payload length.
  - Validates each payload character is a hex digit.

  const String hexPart = payload.substring(separator + 1);
  if ((hexPart.length() % 2) != 0) {
    return false;
  }

  for (size_t i = 0; i < hexPart.length(); ++i) {
    const char ch = hexPart[i];
    const bool isHexDigit =
      (ch >= '0' && ch <= '9') ||
      (ch >= 'a' && ch <= 'f') ||
      (ch >= 'A' && ch <= 'F');
    if (!isHexDigit) {
      return false;
    }
  }
*/
  return true;
}

}  // namespace

// Global framework instance (used for callbacks)
FrameWeb* myFrameWeb;

/**
 * @brief Constructor of the FrameWeb class
 */
FrameWeb::FrameWeb() {
  myFrameWeb = this;
}

/**
 * @brief Destructor of the FrameWeb class
 */
FrameWeb::~FrameWeb() {
  webSocket.close();
  server.close();
  wifiManager.stopWebPortal();
}

/**
* @brief Get the ESP32 model name as a string
 * 
 * Uses esp_chip_info to determine the specific ESP32 model (e.g., ESP32, ESP32-S2, etc.)
 * and returns a human-readable string. This is useful for setting a default hostname
 * based on the device type.
 *   
* @return char* Pointer to a string containing the ESP32 model name (e.g., "ESP32-S3")
*/
char *egtEspModelName() {
  esp_chip_info_t chip_info;
  esp_chip_info(&chip_info);

  const char *model;
  switch (chip_info.model)
  {
  case CHIP_ESP32:
    model = "ESP32";
    break;
  case CHIP_ESP32S2:
    model = "ESP32-S2";
    break;
  case CHIP_ESP32S3:
    model = "ESP32-S3";
    break;
  case CHIP_ESP32C3:
    model = "ESP32-C3";
    break;
  default:
    model = "ESP32-Unknown";
  }
  return (char *)model;
}

/**
 * @brief Convert current configuration to JSON format
 * @return String JSON string containing all configuration parameters
 * 
 * Creates a JSON document from the current Config struct.
 * Useful for saving or displaying configuration.
 */
String FrameWeb::JsonConfig() {
  String configjson;
  // ArduinoJson 7
  JsonDocument rootcfg;
  // Set the values
  rootcfg["HostName"]      = config.HostName;
  JsonArray mac = rootcfg["MacAddress"].to<JsonArray>();
  for (int i=0; i<6; i++)
    mac.add(config.MacAddress[i]);
  rootcfg["ResetWifi"]     = config.ResetWifi;
  rootcfg["LoginName"]     = config.LoginName;
  rootcfg["LoginPassword"] = config.LoginPassword;
  rootcfg["UseToolsLocal"] = config.UseToolsLocal;
  // Transform to string
  serializeJson(rootcfg, configjson);
  return configjson;
}

/**
 * @brief Format size in bytes to human-readable units (B, KB, MB)
 * @param bytes Size in bytes
 * @return String Formatted size (ex: "1.5MB", "256KB", "512B")
 */
String FrameWeb::formatBytes(size_t bytes) { // convert sizes in bytes to KB and MB
  if (bytes < 1024) {
    return String(bytes) + "B";
  } else if (bytes < (1024 * 1024)) {
    return String(bytes / 1024.0) + "KB";
  } else if (bytes < (1024 * 1024 * 1024)) {
    return String(bytes / 1024.0 / 1024.0) + "MB";
  }
  return String(bytes) + "B";
}

/**
 * @brief Recursively list files in a directory
 * @param ret Reference String that will be filled with formatted list
 * @param fs File system (SPIFFS)
 * @param dirname Directory path to list
 * @param levels Number of recursion levels (0 = no recursion)
 * 
 * Displays all files and subdirectories with formatted sizes.
 */
//  Directory list
void FrameWeb::listDir(String& ret, fs::FS &fs, const char * dirname, uint8_t levels) {
  ret += F("Listing directory: ");
  ret += dirname; ret += "\n";
  File root = fs.open(dirname);
  if (!root) { ret += F("Failed to open directory\n");  return;  }
  if (!root.isDirectory()) { ret += F("Not a directory\n\r"); return; }
  File file = root.openNextFile();
  while (file) {
    if (file.isDirectory()) {
      ret += F("  DIR : "); ret += file.name(); ret += "\n";
      if (levels)  listDir(ret, fs, file.name(), levels - 1);
    } else {
      ret += F("  FILE: "); ret += (file.name());  // SPIFFS_OBJ_NAME_LEN=32
      for (uint8_t l=strlen(file.name()); l<32; l+=8)
        ret += "\t";
      ret += F("  SIZE: "); ret += (formatBytes(file.size())); ret += "\n";
    }
    file = root.openNextFile();
  }
  return;
}

/**
 * @brief Determine MIME type of a file by its extension
 * @param filename File name
 * @return String MIME type (ex: "text/html", "image/png", "application/json")
 * 
 * If "download" parameter is present in HTTP request,
 * returns "application/octet-stream" to force download.
 */
String FrameWeb::getContentType(String filename) {
  if (server.hasArg("download"))        { return "application/octet-stream";
  } else if (filename.endsWith(".htm")) { return "text/html";
  } else if (filename.endsWith(".html")){ return "text/html";
  } else if (filename.endsWith(".css")) { return "text/css";
  } else if (filename.endsWith(".js"))  { return "application/javascript";
  } else if (filename.endsWith(".png")) { return "image/png";
  } else if (filename.endsWith(".gif")) { return "image/gif";
  } else if (filename.endsWith(".jpg")) { return "image/jpeg";
  } else if (filename.endsWith(".bmp")) { return "image/bmp";
  } else if (filename.endsWith(".ico")) { return "image/x-icon";
  } else if (filename.endsWith(".xml")) { return "text/xml";
  } else if (filename.endsWith(".pdf")) { return "application/x-pdf";
  } else if (filename.endsWith(".zip")) { return "application/x-zip";
  } else if (filename.endsWith(".gz"))  { return "application/x-gzip"; }
  return "text/plain";
}

/**
 * @brief Save configuration to config.json file on SPIFFS
 * @param filename Configuration file path
 * @param config Config structure to save
 * @return String Confirmation or error message
 */
// Save config file
String FrameWeb::saveConfiguration(const char *filename, const Config &config) {
  File file = SPIFFS.open(filename, "w");
  if (!file)
    return F("Can't write in Config file.");
  file.print(JsonConfig());
  file.close();
  return F("Config file has been saved.");
}

/**
 * @brief Start SPIFFS (SPI Flash File System)
 * 
 * Automatically formats SPIFFS if not formatted.
 * Sets bit 0 of initSetupState on success.
 */
// Start SPIFFS & Read config file
void FrameWeb::startSPIFFS() {
  if (SPIFFS.begin()==false){
    FDBXLN(F("SPIFFS was not formatted."));
    SPIFFS.format();
    SPIFFS.begin();
  } 
  initSetupState = initSetupState | (1<<0);
}

/**
 * @brief Load configuration from config.json
 * @param filename Configuration file path
 * @param config Reference to Config structure to fill
 * @param hname Optional hostname (replaces file value if provided)
 * 
 * If file is missing or invalid, uses default values:
 *  - HostName: esp32 model name or value passed as parameter
 *  - MAC: hardware WiFi MAC address
 *  - LoginName/Password: "admin"/"admin"
 *  - UseToolsLocal: true
 * 
 * On JSON error, automatically creates file with defaults.
 */
void FrameWeb::loadConfiguration(const char *filename, Config &config, const char* hname) {
  // Open file for reading configuration
  File file = SPIFFS.open(filename, "r");
  if (!file)
    FDBXLN(F(" Config file is absent."));
  size_t size = file.size();
  if (size > 1024)
    FDBXLN(F(" Config file too large."));
  // allocate buffer for loading config
  std::unique_ptr<char[]> buf(new char[size]);
  file.readBytes(buf.get(), size);
  // ArduinoJson 7
  JsonDocument rootcfg;
  auto error = deserializeJson(rootcfg, buf.get());
  // Set config or defaults
  uint8_t hardwareMacAddess[6];
  esp_read_mac(hardwareMacAddess, ESP_MAC_WIFI_STA);
  strlcpy(config.HostName, rootcfg["HostName"] | ((hname!=NULL)?(hname):(egtEspModelName())),sizeof(config.HostName));
  JsonArray mac = rootcfg["MacAddress"];
  for (int i=0; i<6; i++)
     config.MacAddress[i] = mac[i] | hardwareMacAddess[i];
  config.ResetWifi = rootcfg["ResetWifi"] | false;
  strlcpy(config.LoginName, rootcfg["LoginName"] | "admin",sizeof(config.LoginName));
  strlcpy(config.LoginPassword, rootcfg["LoginPassword"] | "admin",sizeof(config.LoginPassword));
  config.UseToolsLocal = rootcfg["UseToolsLocal"] | true;
  if ( error ) {
    FDBXLN(F("Error reading config file."));
    String ret = saveConfiguration(filename, config);
    FDBXLN(ret);
  } else {
    initSetupState = initSetupState | (1<<2);
  }
}

/**
 * @brief Start WiFiManager
 * 
 * Manages WiFi connection with following features:
 *  - Automatically connect to saved network
 *  - Enable Access Point (AP) if connection fails
 *  - Allow user to select WiFi via web interface
 *  - Configure custom MAC address
 *  - Restart if connection fails after timeout
 * 
 * Note: ConfigModeCallback is called when entering AP mode
 */
// Start WiFiManager
void FrameWeb::startWifiManager() {
#ifdef LOG_FRAMEWEB_ENABLED
  wifiManager.setDebugOutput(true);
#else
  wifiManager.setDebugOutput(false);
#endif
  //! Warning MacAddress must be UNICAST frame that is bit 0 of first byte must be equals zero
  if ((config.MacAddress[0]&0x01)==0x01) {
    FDBXERR("WARNING: Mac address (%s) is not UNICAST!", bytesToHex(config.MacAddress, 6).c_str());
  }
  esp_base_mac_addr_set(config.MacAddress); // Wifi_STA=mac  wifi_AP=mac+1  BT=mac+2

  //Forcer à effacer les donnees WIFI dans l'eprom , permet de changer d'AP à chaque demmarrage ou effacer les infos d'une AP dans la memoire ( a valider , lors du premier lancement  )
  if (config.ResetWifi)  {
    //!\ Logging and Passwd stay in Flash
    wifiManager.resetSettings();
  }
  //set config save notify callback
  wifiManager.setSaveConfigCallback(saveConfigCallback);
  //set callback that gets called when connecting to previous WiFi fails, and enters Access Point mode

  wifiManager.setAPCallback(configModeCallback);

  // Force host name
  WiFi.setHostname(config.HostName);
  
  if ( ! wifiManager.autoConnect( config.HostName) ) {
    FDBXLN(F("Failed to connect (timeout)."));
    delay(3000);
    //reset and try again, or maybe put it to deep sleep
    ESP.restart();
    delay(5000);
  }
  // Wait for connection
  FDBXLN(F("Waiting for WiFi connection..."));
  while (WiFi.status() != WL_CONNECTED) {
    delay(500); FDBX(".");
  }
  if (WiFi.status() == WL_CONNECTED)
    initSetupState = initSetupState | (1<<2);
}

/**
 * @brief Start OTA (Over-The-Air update) service
 * 
 * Enables firmware update without USB cable:
 *  - Hostname: device name (for Arduino IDE)
 *  - Password: authentication for OTA
 * 
 * Sets bit 3 of initSetupState on success.
 */
// Start OverTheAir firmware uppload
void FrameWeb::startOTA() {
  // ArduinoOTA.setPort(8266); default is 8266
  // Hostname defaults to esp8266-[ChipID]
  ArduinoOTA.setHostname(config.HostName);
  ArduinoOTA.setPassword(config.LoginPassword);
  // Password can be set with it's md5 value as well
  // MD5(admin) = 21232f297a57a5a743894a0e4a801fc3
  // ArduinoOTA.setPasswordHash("21232f297a57a5a743894a0e4a801fc3");
  ArduinoOTA.begin();
  initSetupState = initSetupState | (1<<3);
}

/**
 * @brief Display HTTP arguments and headers received (DEBUG)
 * 
 * Useful for analyzing HTTP requests during development.
 * Displays all POST/GET arguments and HTTP headers.
 */
// Show HTML Arguments and Header (use for debugging)
void FrameWeb::showAH() {
	String m = "Nbr of args:";	m+=server.args();	m+="\n\r";
	for(int i = 0; i < server.args(); i++) {
		m+="Arg["+(String)i+"]=";		m+=server.argName(i)+":";	m+=server.arg(i)+"\n\r";
	}
	FDBX(m);
	String mm = "Nbr of headers:";	mm+=server.headers();	mm+="\n\r";
	for(int i = 0; i < server.headers(); i++) {
		mm+="Header["+(String)i+"]=";		mm+=server.headerName(i)+":";	mm+=server.header(i)+"\n\r";
	}
	FDBX(mm);
	FDBXMF("hostHeader: %s", server.hostHeader().c_str());
}

/**
 * @brief Convert WiFi error code to readable string
 * @param err WiFi error code
 * @return const char* Error description
 */
// Return Wifi Status code as String
const char* FrameWeb::wifiStatus(int err) {
  switch (err) {
    case 0: return "WL_IDLE_STATUS"; break;
    case 1: return "WL_NO_SSID_AVAIL"; break;
    case 2: return "WL_SCAN_COMPLETED"; break;
    case 3: return "WL_CONNECTED"; break;
    case 4: return "WL_CONNECT_FAILED"; break;
    case 5: return "WL_CONNECTION_LOST"; break;
    case 6: return "WL_DISCONNECTED"; break;
  }
  String ret = "wifi_Err="+String(err);
  return ret.c_str();
}

/**
 * @brief Convert HTTP error code to readable string
 * @param err HTTP or client error code
 * @return const char* Error description
 */
// Return Http some Status code as String
const char* FrameWeb::httpStatus(int err) {
  switch (err) {
    case -1  : return "CONNECTION_REFUSED"; break;
    case -2  : return "SEND_HEADER_FAILED"; break;
    case -3  : return "SEND_PAYLOAD_FAILED"; break;
    case -4  : return "NOT_CONNECTED"; break;
    case -5  : return "CONNECTION_LOST"; break;
    case -11 : return "READ_TIMEOUT"; break;
    case 200 : return "OK"; break;
  }
  String ret = "http_Code="+String(err);
  return ret.c_str();
}

/**
 * @brief Convert reset reason code to readable string
 * @param reason ESP32 reset reason code
 * @return const char* Reset reason description
 * 
 * Examples: POWERON_RESET, SW_RESET, DEEPSLEEP_RESET, etc.
 */
const char*  FrameWeb::resetReason(int reason) {
  switch ( reason) {
    case 1 : return "POWERON_RESET"; break;          /**<1, Vbat power on reset*/
    case 3 : return "SW_RESET"; break;               /**<3, Software reset digital core*/
    case 4 : return "OWDT_RESET"; break;             /**<4, Legacy watch dog reset digital core*/
    case 5 : return "DEEPSLEEP_RESET"; break;        /**<5, Deep Sleep reset digital core*/
    case 6 : return "SDIO_RESET"; break;             /**<6, Reset by SLC module, reset digital core*/
    case 7 : return "TG0WDT_SYS_RESET"; break;       /**<7, Timer Group0 Watch dog reset digital core*/
    case 8 : return "TG1WDT_SYS_RESET"; break;       /**<8, Timer Group1 Watch dog reset digital core*/
    case 9 : return "RTCWDT_SYS_RESET"; break;       /**<9, RTC Watch dog Reset digital core*/
    case 10 : return "INTRUSION_RESET"; break;       /**<10, Instrusion tested to reset CPU*/
    case 11 : return "TGWDT_CPU_RESET"; break;       /**<11, Time Group reset CPU*/
    case 12 : return "SW_CPU_RESET"; break;          /**<12, Software reset CPU*/
    case 13 : return "RTCWDT_CPU_RESET"; break;      /**<13, RTC Watch dog Reset CPU*/
    case 14 : return "EXT_CPU_RESET"; break;         /**<14, for APP CPU, reseted by PRO CPU*/
    case 15 : return "RTCWDT_BROWN_OUT_RESET"; break;/**<15, Reset when the vdd voltage is not stable*/
    case 16 : return "RTCWDT_RTC_RESET"; break;      /**<16, RTC Watch dog reset digital core and rtc module*/
    default : return "NO_MEAN"; break;
  }
  return "No_Mean";
}

/**
 * @brief Start WebSocket server on port 81
 * 
 * Enables bidirectional real-time communication with clients.
 * Events are processed via the webSocketEvent() callback function.
 * 
 * Sets bit 4 of initSetupState on success.
 */
// Start webSocket
void FrameWeb::startWebSocket() {
  webSocket.begin();
  webSocket.onEvent(webSocketEvent);
  initSetupState = initSetupState | (1<<4);
}

String FrameWeb::simpleUpload() {
  // Build built-in upload page from pre-generated chunks.
  String message = decodeHtmlChunk(HTTP_HEADAL);
   message += decodeHtmlChunk(HTTP_BODYUP);
  return message;
}

String FrameWeb::simpleIndex() {
  // Build built-in tools page and append external custom tools fragment.
  String message = decodeHtmlChunk(HTTP_HEADAL);
  message += decodeHtmlChunk(HTTP_BODYID);
  message += decodeHtmlChunk(HTTP_BODYI0);
  message += externalHtmlTools;
  message += decodeHtmlChunk(HTTP_BODYI1);
  return message;
}

String FrameWeb::simpleFirmware() {
  // Build built-in firmware update page.
  String message = decodeHtmlChunk(HTTP_HEADAL);
  message += decodeHtmlChunk(HTTP_FIRM0);
  return message;
}

String FrameWeb::zipString(const String& input) {
  // Encode plain text to FrameWeb payload format:
  //   <original_size>:<HEX-ENCODED-ZLIB-BYTES>
  // Implementation detail:
  // - Uses low-level tdefl API.
  // - Allocates compressor state on heap to avoid ROM internal MZ_MALLOC path,
  //   which can fail on ESP32-S3 without PSRAM (~164KB compressor structure).
  const size_t sourceLength = input.length();
  const String header = String(static_cast<unsigned long>(sourceLength)) + ":";

  if (sourceLength == 0) {
    return header;
  }

  const int compressFlags = TDEFL_WRITE_ZLIB_HEADER | TDEFL_DEFAULT_MAX_PROBES;
  const size_t outCapacity = sourceLength + (sourceLength / 10) + 256;

  std::unique_ptr<uint8_t[]> outBuf(new (std::nothrow) uint8_t[outCapacity]);
  std::unique_ptr<tdefl_compressor> comp(new (std::nothrow) tdefl_compressor());

  if (!outBuf || !comp) {
    FDBXERR("zipString: allocation failed (heap pressure). freeHeap=%u\n\r", ESP.getFreeHeap());
    return String();
  }

  if (tdefl_init(comp.get(), nullptr, nullptr, compressFlags) != TDEFL_STATUS_OKAY) {
    FDBXERR("zipString: init failed.");
    return String();
  }

  size_t inSize = sourceLength;
  size_t outSize = outCapacity;
  const tdefl_status status = tdefl_compress(comp.get(),
    reinterpret_cast<const void*>(input.c_str()), &inSize,
    outBuf.get(), &outSize,
    TDEFL_FINISH);

  if (status != TDEFL_STATUS_DONE) {
    FDBXERR("zipString: compression failed. status=%s\n\r",String((int)status));
    return String();
  }

  // outSize is remaining free bytes after compression.
  const size_t compressedLength = outCapacity - outSize;
  return header + bytesToHex(outBuf.get(), compressedLength);
}

String FrameWeb::unzipString(const String& input) {
  // Decode FrameWeb payload format:
  //   <original_size>:<HEX-ENCODED-ZLIB-BYTES>
  // Implementation detail:
  // - Uses tinfl_decompress.
  // - Allocates tinfl_decompressor on heap because the ROM helper
  //   tinfl_decompress_mem_to_mem() uses large stack state on ESP32-S3.
  const int separator = input.indexOf(':');
  if (separator < 0) {
    FDBXLN(F("unzipString invalid payload header."));
    return String();
  }

  const String sizeToken = input.substring(0, separator);
  for (size_t i = 0; i < sizeToken.length(); ++i) {
    if (sizeToken[i] < '0' || sizeToken[i] > '9') {
      FDBXLN(F("unzipString invalid size token."));
      return String();
    }
  }

  const size_t expectedLength = static_cast<size_t>(strtoul(sizeToken.c_str(), nullptr, 10));
  const String hexPayload = input.substring(separator + 1);
  if (expectedLength == 0) {
    return hexPayload.length() == 0 ? String("") : String();
  }

  if ((hexPayload.length() % 2) != 0) {
    FDBXLN(F("unzipString invalid hex payload length (must be even)."));
    return String();
  }

  const size_t compressedLength = hexPayload.length() / 2;
  std::unique_ptr<uint8_t[]> compressed(new uint8_t[compressedLength]);
  if (!hexToBytes(hexPayload, compressed.get(), compressedLength)) {
    FDBXLN(F("unzipString invalid hex payload."));
    return String();
  }

  std::unique_ptr<uint8_t[]> output(new uint8_t[expectedLength + 1]);

  // Allocate tinfl_decompressor on heap to avoid stack overflow:
  // tinfl_decompress_mem_to_mem() allocates tinfl_decompressor (~11KB) on the ROM stack,
  // which overflows the loopTask default 8KB stack on ESP32-S3.
  std::unique_ptr<tinfl_decompressor> decomp(new (std::nothrow) tinfl_decompressor());
  if (!decomp) {
    FDBXERR("unzipString: decompressor alloc failed. freeHeap=%u\n\r", ESP.getFreeHeap());
    return String();
  }
  tinfl_init(decomp.get());

  size_t inBufSize = compressedLength;
  size_t outBufSize = expectedLength;
  const tinfl_status tstatus = tinfl_decompress(
    decomp.get(),
    compressed.get(), &inBufSize,
    output.get(), output.get(), &outBufSize,
    TINFL_FLAG_PARSE_ZLIB_HEADER | TINFL_FLAG_USING_NON_WRAPPING_OUTPUT_BUF
  );

  const size_t outputLength = (tstatus == TINFL_STATUS_DONE) ? outBufSize : 0;

  if (outputLength == 0 || outputLength != expectedLength) {
    FDBXLN("unzipString decompression failed. status=" + String((int)tstatus)
      + " inUsed=" + String(inBufSize)
      + " outLen=" + String(outputLength)
      + " expected=" + String(expectedLength));
    return String();
  }

  output[outputLength] = '\0';
  return String(reinterpret_cast<char*>(output.get()));
}

String FrameWeb::decodeHtmlChunk(const char* chunk) {
  // Unified read path for generated HTTP_* chunks.
  // Handles both plain HTML and FrameWeb zip payload transparently.
  // Safety fallback: if payload looks zipped but decode fails, return raw
  // chunk to avoid blank built-in pages.
  const String raw = FPSTR(chunk);
  FDBXLN("decodeHtmlChunk len="+String(raw.length())+" zipped="+String(isZippedString(raw)));
  if (!isZippedString(raw)) {
    return raw;
  }

  const String decoded = unzipString(raw);

  // Keep raw payload when decode fails to avoid returning an empty page fragment.
  return (decoded.length() == 0 && raw != "0:") ? raw : decoded;
}


// Handle Web server ----- used in startWebServer -------------------------------------------------------------------
bool FrameWeb::handleFileRead(String path) {               // send the right file to the client (if it exists)
  FDBXLN("handleFileRead path:" + path);
  if (path.endsWith("/")) path += "index.html";            // If a folder is requested, send the index file
  String contentType = getContentType(path);               // Get the MIME type
  String pathWithGz = path + ".gz";
  if (SPIFFS.exists(pathWithGz) || SPIFFS.exists(path)) {  // If the file exists, either as a compressed archive, or normal
    if (SPIFFS.exists(pathWithGz))                         // If there's a compressed version available
      path += ".gz";                                       // Use the compressed verion
    File file = SPIFFS.open(path, "r");                    // Open the file
    server.streamFile(file, contentType);                  // Send it to the client
    file.close();                                          // Close the file again
    FDBXLN("\tSent file: " + path);
    return true;
  } else {                                                 // Otherwise build answer locally
    if (config.UseToolsLocal) {
      if (path.endsWith("/index.html")){  // Tools                 // For default index.html page after authentification
        if (!server.authenticate(config.LoginName, config.LoginPassword)) {
           server.requestAuthentication();
           return true;
        }
        server.send(200, "text/html", simpleIndex() );     // If not upload.html in FS send light
        return true;
      }
      if (path.endsWith("/update")){                       // return index page which is stored in serverIndex
        if (!server.authenticate(config.LoginName, config.LoginPassword)) {
          server.requestAuthentication();
          return true;
        }
        server.sendHeader("Connection", "close");
        server.send(200, "text/html", simpleFirmware());
        return true;
      }
    }
  }
  FDBXLN("\tFile Not Found: " + path);                  // If the file doesn't exist, return false
  return false;
}

void FrameWeb::handleFileUpload(){                      // upload a new file to the SPIFFS
  HTTPUpload& upload = server.upload();
  String path;
  if(upload.status == UPLOAD_FILE_START){
    path = upload.filename;
    if ( path.length() < 3 ) {
      server.send(500, "text/plain", "Couldn't create file:["+path+"] invalid name.");
      return;
    }
    if(!path.startsWith("/")) path = "/"+path;
    if(!path.endsWith(".gz")) {                          // The file server always prefers a compressed version of a file
      String pathWithGz = path+".gz";                    // So if an uploaded file is not compressed, the existing compressed
      if(SPIFFS.exists(pathWithGz))                      // version of that file must be deleted (if it exists)
         SPIFFS.remove(pathWithGz);
    }
    FDBXMF("handleFileUpload Name: %s\n\r", path.c_str());
    fsUploadFile = SPIFFS.open(path, "w");               // Open the file for writing in SPIFFS (create if it doesn't exist)
    path = String();
  } else if(upload.status == UPLOAD_FILE_WRITE){
    if(fsUploadFile)
      fsUploadFile.write(upload.buf, upload.currentSize); // Write the received bytes to the file
  } else if(upload.status == UPLOAD_FILE_END){
    if(fsUploadFile) {                                    // If the file was successfully created
      fsUploadFile.close();                               // Close the file again
      FDBXMF("handleFileUpload Size: %d\n\r", upload.totalSize);
      server.sendHeader("Location","/success.html");      // Redirect the client to the success page
      server.send(303);
    } else {
      server.send(500, "text/plain", "Couldn't upload file:["+path+"] in SPIFFS.");
    }
  }
}

String FrameWeb::textNotFound(){
  String message = "File Not Found\n\r";
  message += "URI: ";
  message += server.uri();
  message += " Method: ";
  message += (server.method() == HTTP_GET)?"GET":"POST";
  message += " Arguments: ";
  message += server.args();
  message += "\n\r";
  for (uint8_t i=0; i<server.args(); i++)
    message += " " + server.argName(i) + ": " + server.arg(i) + ",";
  message += "\n\r";
  return message;
}

void FrameWeb::handlePost() {
  if (server.arg("cmd")!="") {
      if (!server.authenticate(config.LoginName, config.LoginPassword)) {
        server.requestAuthentication();
        return;
      }
      FDBXMF("cmd=%s\n\r", server.arg("cmd").c_str());
      if (server.arg("cmd") == "save-config" ) saveConfiguration(filename, config);
      if (server.arg("cmd") == "reset-wifi" ) ResetWifi = true;
      if (server.arg("cmd") == "restart" ) RebootAsap = true;
      if (server.arg("cmd") == "restore" ) RestoreAsap = true;
  }
  server.sendHeader("Location","/");      // Redirect the client to the index page
  server.send(303);
  return;
}

void FrameWeb::handleNotFound(){ // if the requested file or page doesn't exist, return a 404 not found error
  if(!handleFileRead(server.uri())){          // check if the file exists in the flash memory (SPIFFS), if so, send it
    server.send(404, "text/plain", textNotFound());
  }
}

//  Directory list
void FrameWeb::explorer(String& ret, fs::FS &fs, const char * dirname, uint8_t levels) {
  File root = fs.open(dirname);
  if (!root) {  return;  }
  if (!root.isDirectory()) { return; }
  File file = root.openNextFile();
  // For each file in the directory, add an entry to the HTML list with file name, size, and action buttons
  while (file) {
    if (file.isDirectory()) {
      if (levels)  explorer(ret, fs, file.name(), levels - 1);
    } else {
      String strf = (file.name());
      String filelist = FPSTR(HTTP_EXPL1);
      filelist.replace("##F##", strf);
      filelist.replace("##S##",  formatBytes(file.size()) );
      ret += filelist;
    }
    file = root.openNextFile();
  }
  return;
}

void FrameWeb::download(String filename) {
  File download = SPIFFS.open(filename);
  if (download) {
    server.sendHeader("Content-Type", "text/text");
    server.sendHeader("Content-Disposition", "attachment; filename="+filename);
    server.sendHeader("Connection", "close");
    server.streamFile(download, "application/octet-stream");
    download.close();
    return;
  }
  server.send(500, "text/plain", F("500: couldn't download file"));
}

void FrameWeb::sendLs() {
  String ls;
  listDir(ls, SPIFFS, "/", 0);
  server.send(200, "text/plain", ls);
}

void FrameWeb::upload_get() {
  if (!server.authenticate(config.LoginName, config.LoginPassword)) {
    server.requestAuthentication();
    return;
  }
  if (!handleFileRead("/upload.html")) {    // upload.html exist on FS
    if (config.UseToolsLocal) {
      server.send(200, "text/html", simpleUpload() ); // If not upload.html in FS send lightweight
      return;
    }
    else {
      server.send(404, "text/plain", "FileNotFound");
      return;
    }
  }
}

void FrameWeb::upload_post() {
  server.send(200, "text/plain", "");
}

void FrameWeb::exploreWeb() {
#ifdef LOG_FRAMEWEB_ENABLED
  showAH();
#endif
  if (!server.authenticate(config.LoginName, config.LoginPassword)) 
    return server.requestAuthentication();
  if (server.arg("cmd")=="remove") { 
    if (server.arg("file") != "" ) SPIFFS.remove("/"+server.arg("file"));
  }
  if (server.arg("cmd")=="download") {
    if (server.arg("file") != "" ) download("/"+server.arg("file"));
  }
  // Return list of files in table
  String msg = decodeHtmlChunk(HTTP_HEADAL);
  msg += decodeHtmlChunk(HTTP_EXPL0);

  // old
  //String msg = FPSTR(HTTP_HEADAL);
  //msg += FPSTR(HTTP_EXPL0);
  
  explorer(msg, SPIFFS, "/", 0);
  msg += F("</div></div><div style='text-align: center; margin-top: 20px;'><button onclick=\"window.location='/';\">Back</button></div></div></body></html>");
  server.send(200, "text/html", msg);
}

void FrameWeb::update() {
  server.sendHeader("Connection", "close");
  server.send(200, "text/plain", (Update.hasError())?"FAIL":"OK");
  ESP.restart();
}

void FrameWeb::update2() {
  HTTPUpload& upload = server.upload();
  if(upload.status == UPLOAD_FILE_START){
    FDBXMF("Update: %s\n\r", upload.filename.c_str());
    if(!Update.begin(UPDATE_SIZE_UNKNOWN)){ //start with max available size
      Update.printError(Serial);
    }
  } else if(upload.status == UPLOAD_FILE_WRITE){
    /* flashing firmware to ESP*/
    if(Update.write(upload.buf, upload.currentSize) != upload.currentSize){
      Update.printError(Serial);
    }
  } else if(upload.status == UPLOAD_FILE_END){
    if(Update.end(true)){ //true to set the size to the current progress
      FDBXMF("Update Success: %u\n\rRebooting...\n\r", upload.totalSize);
    } else {
      Update.printError(Serial);
    }
  }
}

// Start web server -------------------------------------------------------------------
void FrameWeb::startWebServer(){

  // POST
  server.on("/post",  HTTP_POST, []() {        // If a POST request is sent to the /edit.html address,
     myFrameWeb->handlePost();
  });

  // Simple command wihout pwd
  server.on("/ls", [](){                      // Get list of file in FS
    myFrameWeb->sendLs();
  });

  /* handling uploading firmware file */
  server.on("/update", HTTP_POST, [](){
    myFrameWeb->update();
  },[](){
    myFrameWeb->update2();
  });

  // handling upload file
  server.on("/upload", HTTP_GET, []() {        // Upload
    myFrameWeb->upload_get();
  });

  server.on("/upload", HTTP_POST, []() {       // Back after selection
    myFrameWeb->upload_post();
    },[](){
     myFrameWeb->handleFileUpload();
    });

  server.onNotFound([]() {
    myFrameWeb->handleNotFound();
  });

  server.on("/explorer", [](){                  // Get list of file in FS
    myFrameWeb->exploreWeb();
  });

  server.begin();
  initSetupState = initSetupState | (1<<5);
}

// Start MDNS
void FrameWeb::startMDNS() {
  // - first argument is the domain name, in this example   the fully-qualified domain name is "esp32.local"
  // - second argument is the IP address to advertise   we send our IP address on the WiFi network
  if (!MDNS.begin(config.HostName))
    FDBXLN(F("Error setting up MDNS responder!"));
  FDBXMF("mDNS responder started: %s\n\r", config.HostName);
  MDNS.addService("http",  "tcp", 80);
  MDNS.addService("ws",    "tcp", 81);
  MDNS.addService("esp32", "tcp", 8888); // Announce esp32 service port 8888 TCP
  initSetupState = initSetupState | (1<<6);
}

// Arduino core -------------------------------------------------------------
void FrameWeb::setup( /*void (*func)(WiFiManager* myWiFiManager),*/ const char* hostname) {
  FDBXMF("FrameWeb::setup started version: %s\n\r", FrameVersion);
  startSPIFFS();                   // Start FS (list all contents)
  loadConfiguration(filename, config, hostname); // Read config file
  startWifiManager();              // Start a Wi-Fi access point, and try to connect
  startOTA();                      // Start the OTA service
  startWebSocket();                // Start a WebSocket server
  startWebServer();                // Start a HTTP server with a file read handler and an upload handler
  startMDNS();                     // Start the mDNS responder  //DBXLN(FPSTR(FrameVersion));
  FDBXMF("FrameWeb::setup ready  IP: %s\n\r", WiFi.localIP().toString().c_str());
  FDBXMF("FrameWeb::setup ready MAC: %s\n\r", WiFi.macAddress().c_str() );
  
}

void FrameWeb::loop() {
  
  server.handleClient();         // constantly check for events
  webSocket.loop();              // constantly check for websocket events
  ArduinoOTA.handle();           // listen for OTA events
  if (ResetWifi) {
    wifiManager.resetSettings(); // BUG the stored ssid no cleared !!
    wifi_init_config_t cfg = WIFI_INIT_CONFIG_DEFAULT(); //load the flash-saved configs
    esp_wifi_init(&cfg); //initiate and allocate wifi resources (does not matter if connection fails)
    delay(2000); //wait a little bit
    if(esp_wifi_restore() != ESP_OK) {
      FDBXLN("WiFi is not initialized by esp_wifi_init");
    } else {
      /* It appears that the code provided is not valid C++ code. The text "FDBXLN" and " */
      FDBXLN("WiFi Configurations Cleared!");
    }
    wifiManager.startConfigPortal(config.HostName, NULL);
    ESP.restart();
  }
  if (RebootAsap) { 
    ESP.restart(); // Restart in case of error
  }
  if (RestoreAsap) {             // Reset to factory settings
    FDBXLN(F("Format SPIFS..."));
    SPIFFS.format();
    wifiManager.resetSettings(); // BUG the stored ssid no cleared !!
    ESP.restart();
  }
}