/*
  * @file FrameWeb.cpp
  * @brief Implementation of the ESP32 Web Framework
  * 
  * This file contains the complete implementation of the web system for ESP32,
  * including WiFi management, HTTP server, OTA and WebSocket handling.
  *
  * Generated HTML payload mode:
  * - Controlled by custom_out_zip in platformio.ini.
  * - custom_out_zip = plain keeps HTTP_* chunks as plain HTML.
  * - custom_out_zip = zip stores every chunk as FrameWeb zip payloads:
  *   "<raw_size>:<hex_zlib_payload>".
  * - custom_out_zip = zip_if_best stores, for each chunk, the smallest
  *   payload between plain HTML and FrameWeb zip format.
  *
  * Runtime decoding is automatic through decodeHtmlChunk().
*/

// Zip generation mode is controlled by platformio.ini custom_out_zip.
// LOG_FRAMEWEB_ENABLED enables FrameWeb debug output (prefix [F]).
#include "FrameWeb.h"
#include <rom/miniz.h>

// This block is auto-regenerated by extra_script.py at pre-build.
// Do not edit lines between the two markers below.

 
// ============ Pre-generated HTML (generated from FrameWeb.html) ============
// These character strings PROGMEM are stored in Flash to save RAM
//! Warning: The section between 'Start Generated' and 'End Generated' is auto-generated.
//! It is generated from src/FrameWeb.html. Any manual changes will be lost at the next generation.
//! To modify HTML content, edit src/FrameWeb.html and regenerate FrameWeb.cpp using extra_script.py.
//! See platformio.ini for the extra_script.py configuration used during the build process.
//! stats: len=stored string content size (inside quotes), source=original UTF-8 HTML size, payload=stored UTF-8 payload size (plain or size:HEX_ZLIB), gain=source-payload
//---- Start Generated from src/FrameWeb.html file --- 2026-05-19 22:02:38 | sha256=1265f822563af038a373fbf32e21c04ae22199d5df85c1d93716d3e2ccb8e671 | zip_mode=zip_if_best
const char HTTP_HEADAL[] PROGMEM = "1762:78DA8D554D73DA3010FD2BEA7000779063F3156220D33425D766A6E9A14761C9468D2D792441A00CFFBD2BC9184248DAF104B26B6977DFDBB7CBF4D3B7EFF74FBF1EE76869CAE276BA6484DE4E4B66084A9744696666ED9F4F0F78DCAEBD82946CD65E73F6524965DA2895C23001A75E3835CB19656B9E32EC8C2EE2821B4E0AAC5352B0591C4610C57053B0DBF98FC77E6F7AE58DA9365BF84A949406ED30AE142F89DA26A835B8BF7B184693C6852951CFD63F24D1E006FC8B1C173C5F1AF06543FB781F37ACB4AE1BFB804B2F09952F098A50AFDAA001FCA97C413A51D73E611CC01145285FE9048DABCD64FF19ED10E4CBB9803B1354114AB9C8DDFF0BB9C19AFF71E6422ACA1406D704ED17926EE15A0684E08C94BC0000770AE07791264263CD14CFE03E499F7325578226684D54E78821384914475006905B480538FAFD3E24082DD7840BA65C751BCF72826E2277B8A917919591AF13B5B2CCA6F6E51E90FAECDE0A6A60354FFE95B74ECBEAB94CFB50B3D47029B0EB5F1759D5B8AA1A428C91D0004BB69605A7A845293D94D8BC8E87365A1DFCE8F5399A98866D0C26C010604B416A4C35486A7E7CB5B544823769FA75C0D81678424A0154128573CB00C4EDC4FD21657917B5C6D7F7F3F9D7EE59DCE0D80FC7E6B1570EC619B9434F14F13C593D7651984955629BBE423BCA755510D048AE3850633F319C029F6116D8AA141026CE54DDCE9C5487548E0C175337949C29E7A2CAEC8DA0A9B460198CCDA069D1398B678006478DBD6ED53E5CACC0140760A84196156C53176EA7CAD9F84559DB7E4ED0EF95363CDBE27A89F81B98096AC7C90545BB06188440F1E832B863D5AF5AE421244848C12E024A574ADBE395E45E5846C1A872DB3318A4B0AF27751DC952AEBDC2DFCBED5653E08663AB8168EC5BAFCFEEB4B2281BFF5B3E97D83E0C5F066B5248C3F461DBC03A6210A777BA3246A3D1DB154052FA6EFBA1304207ECBF0ADB7F2919E504754EB6D0F5081A14A0DD0792FF40E416D7998C2E8B431BA2CC619A4FD1873DC54A78B19F5EF99F93E995FB31FB0B17B95937";
//---- len : 1537 bytes | source=1762 | payload=1537 | gain=225 (12.8%)
const char HTTP_BODYUP[] PROGMEM = "<body><div class='container'><header><h1>ESP32 Uploader</h1></header><p class='message'>Transfer a file to SPIFFS. Gzip supported.</p><div class='section'><div class='section-title'>File Upload</div><div class='action-list'><div class='action-item'><div>- Select a file to upload to the EFS.</div><div class='button-group'><form method='post' enctype='multipart/form-data' style='display:flex;gap:8px;align-items:center;flex-wrap:wrap;'><input type='file' name='Choose file' accept='.gz,.html,.ico,.js,.json,.css,.png,.gif,.bmp,.jpg,.xml,.pdf,.htm' style='min-width:200px;'><button type='submit' name='submit'>Upload</button></form></div></div></div></div><div style='text-align:center;'><button onclick=\"window.location='/';\">Back</button></div></div></body></html>";
//---- len : 768 bytes | source=766 | payload=766 | gain=0 (0.0%)
const char HTTP_BODYID[] PROGMEM = "1023:78DAAD93514FC23010C7BF4AC3CBF4812DEAA36389929198986802FA5EDA1B54BB7669AF0CBEBDB715028B98A8E1A56B7BFBDFFDFE775BBEB47257E4526D98D0DCFB4922AC41AE0CB8A4C8D7C025387ADE14E5FCF5EE9695F512A404C916D66A9F6714A065FF5673485183F77C0549F164246CD335D69A554A03331659658391CC1A866B6012364A409A67CD80C18340654D72EE728C0A35E59E5A53A95570BCBB6433E0181C10122906321E555A794CCE0514421D03C5983D3ADB7A609C086B6EC843CFED998AB8E56C9E7EAFB00C889468E56C6828533C9243A195F89C8C5A65A46D536D458F3A4932D836DA3AEAF0FDA828F7FB3C8BBADFE8B5EF94CFE4E8A88A543FB91F987C57D0F676C4A085FD8482A7E172641EB9C3D05CC06C2C927E789A27514F8FC77FC1BF51BBB8DC8F056D1CCBE1AB9C7516E63B4F820B9087BE54071D8B9E0EE94FC4922341F63F50A55CDD7207CC6EC0F5F05C3976F5B278B8BE0871572A1277BBF3BC27EB172F0C69AC";
//---- len : 743 bytes | source=1023 | payload=743 | gain=280 (27.4%)
const char HTTP_BODYI0[] PROGMEM = "842:78DA7552CB6EE3300CFC15DE042CE07A1F5860E128068A457B2EEA43CFB24D3B04F4302C3A5DFF7D292BC9A64D7B31C4C70CC71CEA9E8ED05913E35E45EC988257B5BE4D164C6C51D5CD1A191DDC6FC9A84BE97CDFBED50B93EB42B5D85A5BAA0BD06DFD8C91CDCCBA6CEB0A9EB10D8123F001E1A179FAF5F34E97D278696ECC11E16FF0038D199012112232931F0517E0E1B1B9836FEF61694698F13C630B22F43898C5CA34E37B092CB22407B21885E09601195EE8912E2428C894B84C4FA813AC4C7F78B38721CCAE18E7B04CB2036B5AB420A9BDEA5CAF644C23123A06035D702E691AE6E0B655588A5C097382D43AD1405EE65E4D21B202877C08FD398ABC5ADCAB9EE264CD5AC160F1DF0E463355F0679297B134FA82C4935841879E71DE89A298E7539F1581370E4FCF136322AAE0C70E1CF9E2957A3E48F4FBBB700A3C4C49111C8D5DA4D5072F97A1CB9CFD589DB3E9EABFFB9FF745B1B7E836BFD5B5F9C9E02F999145DB40EACAB4ECCCD75AE41ED4F94AE0BAB5CC4BA975BB300B86D729C95A5A47A2FE7E9AEC2A07B1D5A4393973F67DFBBE01817A212B";
//---- len : 830 bytes | source=842 | payload=830 | gain=12 (1.4%)
const char HTTP_BODYI1[] PROGMEM = "<div class='footnotes'><p>* All parameters in config.json are affected.</p><p>** Login, password, and flags reset to default. EFS reformatted.</p><p>*** Device reboots in AP mode to select a new WiFi network.</p></div></div></body></html>";
//---- len : 238 bytes | source=238 | payload=238 | gain=0 (0.0%)
const char HTTP_FIRM0[] PROGMEM = "1815:78DA95956D8FD33810C7BFCA0002A7074DBB7048A7A68D04CBAE3809C4EAE074F70EB9C924F5AD63FB9CC9762BD8EF7EE33829ED2DF4746FD2C49EF9CF6F1EEC2ED7B6DCE5CB52DD40A165DBAE44610D4965D08B7CB94159A2E7DFB3FCE2E3D58BE770A97CB3951EE177574AC2E58C77F83198B951A3C1B695358AC1EBC3A757508D9E5DEF99C21BAC64A7092AEB1B490B48D7CAA4CB993B8269B120658DF8DEE29414698E718F894D8FEC653457844D14CAA710C1F65021F848765F60DD11B140ED6DE75821104383B4B1E54A5C7DF8F849400CB1128F04A02968E7908BC0D929273DCD82C394B5A500C52E9DD356969FC3AA8096769A8D4BD53A2D770BA834DE66504BB7805F1CBF49ADEAC8DE2EA04043E8B3DE68016719C328E33A8218B1525C0F6629D0D14A849C0418D960081952DB471BFDA15166BA55256DF8EBE59CE3B162CC76906CBB75A348E4636DE326F73CD0E743A90E9FFFB37957DED69EA7E574D746EEBFBA9654B59B8619E552EC0B328408C575BEDE9B13DED2B42FE041E9D875BA45556FD87D6D75994161B5F50B78F4F3F9ABCB9773167303D402E68F4FA758594BC612B64CE0F23FA437CAD48B61BA5882B8FD2DC88E2CCFB82AA4D63B9015837C1B3677287B02BC91BEE66E91E5C9787EDC2A6B0AAD8AEBD5C3AD32A5DDA6DA1632CEE34C640FF3D7B2B83EE8DC41266DE195A33CA93AD3573B99C0971BE9FB33092B286DD1351C3EAD912E3486D7D7BB5FCBE468822759F0184B76CA2BB46692A90A92077D80AF5FE1C1E8C7813D52E74D7617F65259961737ECF94EB5DC69F4C93889CF600F8BEC84A9F3180C87EB248938E1B0318AC12D5CB2DC1BFE4C826EDCBDDDF861F3CFF7EFDE12B9DFF0EF8E9BC5CEBC95C6ECBE8330C21E41DC106384A4F82DD5686ADA9CDB860FA55C6B1CEAE93004EC0D58194B98F51F6449EA6C544D43D7CFE364B3B5F83685029EC27B499B942F20532641ED27389BCF27BC2E1E8BECEE2E82DF270EE10E6907D460CCB3495D0BF98AA7690E4F9EC0C1E2125E04F52FFF8DC614010050B7F863FB38EC5049BEA0CA53BCE8BDF5FF02FE91A841DA5A7F0DD1271B34AD4393C45BF91988D970F1C5BD16B97A613426C1FA6EC2FD5ECE8633C007A4FF279C6DA8D1F93FDDC975F4";
//---- len : 1653 bytes | source=1815 | payload=1653 | gain=162 (8.9%)
const char HTTP_EXPL0[] PROGMEM = "<script>function clic(pa, el) {var r = confirm('Are you sure you want to ' + pa + ' ' + el + ' ?');if (r == true) {window.location = '/explorer?cmd=' + pa + '&file=' + el;}}</script><body><div class='container'><header><h1>File Explorer</h1></header><p class='message'>Browse and manage files in the EFS.</p><div class='section'><div class='section-title'>Files</div><div class='action-list'>";
//---- len : 392 bytes | source=392 | payload=392 | gain=0 (0.0%)
const char HTTP_EXPL1[] PROGMEM = "<div class='action-item'><div><a href='##F##'>##F##</a><span style='color: #999;'> (##S##)</span></div><div class='button-group'><button onclick=\"clic('download', '##F##')\">Download</button><button onclick=\"clic('remove', '##F##')\">Remove</button></div></div>";
//---- len : 263 bytes | source=259 | payload=259 | gain=0 (0.0%)
//---- total len : 6424 bytes | source=7097 | payload=6418 | gain=679 (9.6%)
//---- End Generated

namespace {

// ===== Internal zip helper utilities (local to this translation unit) =====
// Purpose:
// - Convert compressed bytes to/from ASCII hex representation.
// - Detect whether a generated chunk is in FrameWeb zip format.

char nibbleToHex(uint8_t nibble) {
  return (nibble < 10) ? static_cast<char>('0' + nibble) : static_cast<char>('A' + (nibble - 10));
}

int hexToNibble(char ch) {
  if (ch >= '0' && ch <= '9') {
    return ch - '0';
  }
  if (ch >= 'a' && ch <= 'f') {
    return 10 + (ch - 'a');
  }
  if (ch >= 'A' && ch <= 'F') {
    return 10 + (ch - 'A');
  }
  return -1;
}

String bytesToHex(const uint8_t* data, size_t length) {
  String hex;
  if (!hex.reserve(length * 2)) {
    return String();
  }

  for (size_t index = 0; index < length; ++index) {
    const uint8_t value = data[index];
    hex += nibbleToHex((value >> 4) & 0x0F);
    hex += nibbleToHex(value & 0x0F);
  }

  return hex;
}

bool hexToBytes(const String& hex, uint8_t* output, size_t outputLength) {
  if ((hex.length() % 2) != 0 || (hex.length() / 2) != outputLength) {
    return false;
  }

  for (size_t index = 0; index < outputLength; ++index) {
    const int high = hexToNibble(hex[index * 2]);
    const int low = hexToNibble(hex[(index * 2) + 1]);
    if (high < 0 || low < 0) {
      return false;
    }
    output[index] = static_cast<uint8_t>((high << 4) | low);
  }

  return true;
}

bool isZippedString(const String& payload) {
  // Fast format detection for FrameWeb zip payloads:
  // "<raw_size>:<hex_zlib_payload>"
  // Current strategy validates only the numeric size prefix and ':' separator
  // to keep this check very cheap for all HTTP_* chunk reads.
  const int separator = payload.indexOf(':');
  if (separator <= 0) {
    return false;
  }

  for (int i = 0; i < separator; ++i) {
    const char ch = payload[i];
    if (ch < '0' || ch > '9') {
      return false;
    }
  }
  /*
  Optional strict validation (kept disabled for speed):
  - Enforces even hex payload length.
  - Validates each payload character is a hex digit.

  const String hexPart = payload.substring(separator + 1);
  if ((hexPart.length() % 2) != 0) {
    return false;
  }

  for (size_t i = 0; i < hexPart.length(); ++i) {
    const char ch = hexPart[i];
    const bool isHexDigit =
      (ch >= '0' && ch <= '9') ||
      (ch >= 'a' && ch <= 'f') ||
      (ch >= 'A' && ch <= 'F');
    if (!isHexDigit) {
      return false;
    }
  }
*/
  return true;
}

}  // namespace

// Global framework instance (used for callbacks)
FrameWeb* myFrameWeb;

/**
 * @brief Constructor of the FrameWeb class
 */
FrameWeb::FrameWeb() {
  myFrameWeb = this;
}

/**
 * @brief Destructor of the FrameWeb class
 */
FrameWeb::~FrameWeb() {
  webSocket.close();
  server.close();
  wifiManager.stopWebPortal();
}

/**
* @brief Get the ESP32 model name as a string
 * 
 * Uses esp_chip_info to determine the specific ESP32 model (e.g., ESP32, ESP32-S2, etc.)
 * and returns a human-readable string. This is useful for setting a default hostname
 * based on the device type.
 *   
* @return char* Pointer to a string containing the ESP32 model name (e.g., "ESP32-S3")
*/
char *egtEspModelName() {
  esp_chip_info_t chip_info;
  esp_chip_info(&chip_info);

  const char *model;
  switch (chip_info.model)
  {
  case CHIP_ESP32:
    model = "ESP32";
    break;
  case CHIP_ESP32S2:
    model = "ESP32-S2";
    break;
  case CHIP_ESP32S3:
    model = "ESP32-S3";
    break;
  case CHIP_ESP32C3:
    model = "ESP32-C3";
    break;
  default:
    model = "ESP32-Unknown";
  }
  return (char *)model;
}

/**
 * @brief Convert current configuration to JSON format
 * @return String JSON string containing all configuration parameters
 * 
 * Creates a JSON document from the current Config struct.
 * Useful for saving or displaying configuration.
 */
String FrameWeb::JsonConfig() {
  String configjson;
  // ArduinoJson 7
  JsonDocument rootcfg;
  // Set the values
  rootcfg["HostName"]      = config.HostName;
  JsonArray mac = rootcfg["MacAddress"].to<JsonArray>();
  for (int i=0; i<6; i++)
    mac.add(config.MacAddress[i]);
  rootcfg["ResetWifi"]     = config.ResetWifi;
  rootcfg["LoginName"]     = config.LoginName;
  rootcfg["LoginPassword"] = config.LoginPassword;
  rootcfg["UseToolsLocal"] = config.UseToolsLocal;
  // Transform to string
  serializeJson(rootcfg, configjson);
  return configjson;
}

/**
 * @brief Format size in bytes to human-readable units (B, KB, MB)
 * @param bytes Size in bytes
 * @return String Formatted size (ex: "1.5MB", "256KB", "512B")
 */
String FrameWeb::formatBytes(size_t bytes) { // convert sizes in bytes to KB and MB
  if (bytes < 1024) {
    return String(bytes) + "B";
  } else if (bytes < (1024 * 1024)) {
    return String(bytes / 1024.0) + "KB";
  } else if (bytes < (1024 * 1024 * 1024)) {
    return String(bytes / 1024.0 / 1024.0) + "MB";
  }
  return String(bytes) + "B";
}

/**
 * @brief Recursively list files in a directory
 * @param ret Reference String that will be filled with formatted list
 * @param fs File system (SPIFFS)
 * @param dirname Directory path to list
 * @param levels Number of recursion levels (0 = no recursion)
 * 
 * Displays all files and subdirectories with formatted sizes.
 */
//  Directory list
void FrameWeb::listDir(String& ret, fs::FS &fs, const char * dirname, uint8_t levels) {
  ret += F("Listing directory: ");
  ret += dirname; ret += "\n";
  File root = fs.open(dirname);
  if (!root) { ret += F("Failed to open directory\n");  return;  }
  if (!root.isDirectory()) { ret += F("Not a directory\n\r"); return; }
  File file = root.openNextFile();
  while (file) {
    if (file.isDirectory()) {
      ret += F("  DIR : "); ret += file.name(); ret += "\n";
      if (levels)  listDir(ret, fs, file.name(), levels - 1);
    } else {
      ret += F("  FILE: "); ret += (file.name());  // SPIFFS_OBJ_NAME_LEN=32
      for (uint8_t l=strlen(file.name()); l<32; l+=8)
        ret += "\t";
      ret += F("  SIZE: "); ret += (formatBytes(file.size())); ret += "\n";
    }
    file = root.openNextFile();
  }
  return;
}

/**
 * @brief Determine MIME type of a file by its extension
 * @param filename File name
 * @return String MIME type (ex: "text/html", "image/png", "application/json")
 * 
 * If "download" parameter is present in HTTP request,
 * returns "application/octet-stream" to force download.
 */
String FrameWeb::getContentType(String filename) {
  if (server.hasArg("download"))        { return "application/octet-stream";
  } else if (filename.endsWith(".htm")) { return "text/html";
  } else if (filename.endsWith(".html")){ return "text/html";
  } else if (filename.endsWith(".css")) { return "text/css";
  } else if (filename.endsWith(".js"))  { return "application/javascript";
  } else if (filename.endsWith(".png")) { return "image/png";
  } else if (filename.endsWith(".gif")) { return "image/gif";
  } else if (filename.endsWith(".jpg")) { return "image/jpeg";
  } else if (filename.endsWith(".bmp")) { return "image/bmp";
  } else if (filename.endsWith(".ico")) { return "image/x-icon";
  } else if (filename.endsWith(".xml")) { return "text/xml";
  } else if (filename.endsWith(".pdf")) { return "application/x-pdf";
  } else if (filename.endsWith(".zip")) { return "application/x-zip";
  } else if (filename.endsWith(".gz"))  { return "application/x-gzip"; }
  return "text/plain";
}

/**
 * @brief Save configuration to config.json file on SPIFFS
 * @param filename Configuration file path
 * @param config Config structure to save
 * @return String Confirmation or error message
 */
// Save config file
String FrameWeb::saveConfiguration(const char *filename, const Config &config) {
  File file = SPIFFS.open(filename, "w");
  if (!file)
    return F("Can't write in Config file.");
  file.print(JsonConfig());
  file.close();
  return F("Config file has been saved.");
}

/**
 * @brief Start SPIFFS (SPI Flash File System)
 * 
 * Automatically formats SPIFFS if not formatted.
 * Sets bit 0 of initSetupState on success.
 */
// Start SPIFFS & Read config file
void FrameWeb::startSPIFFS() {
  if (SPIFFS.begin()==false){
    FDBXLN(F("SPIFFS was not formatted."));
    SPIFFS.format();
    SPIFFS.begin();
  } 
  initSetupState = initSetupState | (1<<0);
}

/**
 * @brief Load configuration from config.json
 * @param filename Configuration file path
 * @param config Reference to Config structure to fill
 * @param hname Optional hostname (replaces file value if provided)
 * 
 * If file is missing or invalid, uses default values:
 *  - HostName: esp32 model name or value passed as parameter
 *  - MAC: hardware WiFi MAC address
 *  - LoginName/Password: "admin"/"admin"
 *  - UseToolsLocal: true
 * 
 * On JSON error, automatically creates file with defaults.
 */
void FrameWeb::loadConfiguration(const char *filename, Config &config, const char* hname) {
  // Open file for reading configuration
  File file = SPIFFS.open(filename, "r");
  if (!file)
    FDBXLN(F(" Config file is absent."));
  size_t size = file.size();
  if (size > 1024)
    FDBXLN(F(" Config file too large."));
  // allocate buffer for loading config
  std::unique_ptr<char[]> buf(new char[size]);
  file.readBytes(buf.get(), size);
  // ArduinoJson 7
  JsonDocument rootcfg;
  auto error = deserializeJson(rootcfg, buf.get());
  // Set config or defaults
  uint8_t hardwareMacAddess[6];
  esp_read_mac(hardwareMacAddess, ESP_MAC_WIFI_STA);
  strlcpy(config.HostName, rootcfg["HostName"] | ((hname!=NULL)?(hname):(egtEspModelName())),sizeof(config.HostName));
  JsonArray mac = rootcfg["MacAddress"];
  for (int i=0; i<6; i++)
     config.MacAddress[i] = mac[i] | hardwareMacAddess[i];
  config.ResetWifi = rootcfg["ResetWifi"] | false;
  strlcpy(config.LoginName, rootcfg["LoginName"] | "admin",sizeof(config.LoginName));
  strlcpy(config.LoginPassword, rootcfg["LoginPassword"] | "admin",sizeof(config.LoginPassword));
  config.UseToolsLocal = rootcfg["UseToolsLocal"] | true;
  if ( error ) {
    FDBXLN(F("Error reading config file."));
    String ret = saveConfiguration(filename, config);
    FDBXLN(ret);
  } else {
    initSetupState = initSetupState | (1<<2);
  }
}

/**
 * @brief Start WiFiManager
 * 
 * Manages WiFi connection with following features:
 *  - Automatically connect to saved network
 *  - Enable Access Point (AP) if connection fails
 *  - Allow user to select WiFi via web interface
 *  - Configure custom MAC address
 *  - Restart if connection fails after timeout
 * 
 * Note: ConfigModeCallback is called when entering AP mode
 */
// Start WiFiManager
void FrameWeb::startWifiManager() {
#ifdef LOG_FRAMEWEB_ENABLED
  wifiManager.setDebugOutput(true);
#else
  wifiManager.setDebugOutput(false);
#endif
  //! Warning MacAddress must be UNICAST frame that is bit 0 of first byte must be equals zero
  if ((config.MacAddress[0]&0x01)==0x01) {
    FDBXERR("WARNING: Mac address (%s) is not UNICAST!", bytesToHex(config.MacAddress, 6).c_str());
  }
  esp_base_mac_addr_set(config.MacAddress); // Wifi_STA=mac  wifi_AP=mac+1  BT=mac+2

  //Forcer à effacer les donnees WIFI dans l'eprom , permet de changer d'AP à chaque demmarrage ou effacer les infos d'une AP dans la memoire ( a valider , lors du premier lancement  )
  if (config.ResetWifi)  {
    //!\ Logging and Passwd stay in Flash
    wifiManager.resetSettings();
  }
  //set config save notify callback
  wifiManager.setSaveConfigCallback(saveConfigCallback);
  //set callback that gets called when connecting to previous WiFi fails, and enters Access Point mode

  wifiManager.setAPCallback(configModeCallback);

  // Force host name
  WiFi.setHostname(config.HostName);
  
  if ( ! wifiManager.autoConnect( config.HostName) ) {
    FDBXLN(F("Failed to connect (timeout)."));
    delay(3000);
    //reset and try again, or maybe put it to deep sleep
    ESP.restart();
    delay(5000);
  }
  // Wait for connection
  FDBXLN(F("Waiting for WiFi connection..."));
  while (WiFi.status() != WL_CONNECTED) {
    delay(500); FDBX(".");
  }
  if (WiFi.status() == WL_CONNECTED)
    initSetupState = initSetupState | (1<<2);
}

/**
 * @brief Start OTA (Over-The-Air update) service
 * 
 * Enables firmware update without USB cable:
 *  - Hostname: device name (for Arduino IDE)
 *  - Password: authentication for OTA
 * 
 * Sets bit 3 of initSetupState on success.
 */
// Start OverTheAir firmware uppload
void FrameWeb::startOTA() {
  // ArduinoOTA.setPort(8266); default is 8266
  // Hostname defaults to esp8266-[ChipID]
  ArduinoOTA.setHostname(config.HostName);
  ArduinoOTA.setPassword(config.LoginPassword);
  // Password can be set with it's md5 value as well
  // MD5(admin) = 21232f297a57a5a743894a0e4a801fc3
  // ArduinoOTA.setPasswordHash("21232f297a57a5a743894a0e4a801fc3");
  ArduinoOTA.begin();
  initSetupState = initSetupState | (1<<3);
}

/**
 * @brief Display HTTP arguments and headers received (DEBUG)
 * 
 * Useful for analyzing HTTP requests during development.
 * Displays all POST/GET arguments and HTTP headers.
 */
// Show HTML Arguments and Header (use for debugging)
void FrameWeb::showAH() {
	String m = "Nbr of args:";	m+=server.args();	m+="\n\r";
	for(int i = 0; i < server.args(); i++) {
		m+="Arg["+(String)i+"]=";		m+=server.argName(i)+":";	m+=server.arg(i)+"\n\r";
	}
	FDBX(m);
	String mm = "Nbr of headers:";	mm+=server.headers();	mm+="\n\r";
	for(int i = 0; i < server.headers(); i++) {
		mm+="Header["+(String)i+"]=";		mm+=server.headerName(i)+":";	mm+=server.header(i)+"\n\r";
	}
	FDBX(mm);
	FDBXMF("hostHeader: %s", server.hostHeader().c_str());
}

/**
 * @brief Convert WiFi error code to readable string
 * @param err WiFi error code
 * @return const char* Error description
 */
// Return Wifi Status code as String
const char* FrameWeb::wifiStatus(int err) {
  switch (err) {
    case 0: return "WL_IDLE_STATUS"; break;
    case 1: return "WL_NO_SSID_AVAIL"; break;
    case 2: return "WL_SCAN_COMPLETED"; break;
    case 3: return "WL_CONNECTED"; break;
    case 4: return "WL_CONNECT_FAILED"; break;
    case 5: return "WL_CONNECTION_LOST"; break;
    case 6: return "WL_DISCONNECTED"; break;
  }
  String ret = "wifi_Err="+String(err);
  return ret.c_str();
}

/**
 * @brief Convert HTTP error code to readable string
 * @param err HTTP or client error code
 * @return const char* Error description
 */
// Return Http some Status code as String
const char* FrameWeb::httpStatus(int err) {
  switch (err) {
    case -1  : return "CONNECTION_REFUSED"; break;
    case -2  : return "SEND_HEADER_FAILED"; break;
    case -3  : return "SEND_PAYLOAD_FAILED"; break;
    case -4  : return "NOT_CONNECTED"; break;
    case -5  : return "CONNECTION_LOST"; break;
    case -11 : return "READ_TIMEOUT"; break;
    case 200 : return "OK"; break;
  }
  String ret = "http_Code="+String(err);
  return ret.c_str();
}

/**
 * @brief Convert reset reason code to readable string
 * @param reason ESP32 reset reason code
 * @return const char* Reset reason description
 * 
 * Examples: POWERON_RESET, SW_RESET, DEEPSLEEP_RESET, etc.
 */
const char*  FrameWeb::resetReason(int reason) {
  switch ( reason) {
    case 1 : return "POWERON_RESET"; break;          /**<1, Vbat power on reset*/
    case 3 : return "SW_RESET"; break;               /**<3, Software reset digital core*/
    case 4 : return "OWDT_RESET"; break;             /**<4, Legacy watch dog reset digital core*/
    case 5 : return "DEEPSLEEP_RESET"; break;        /**<5, Deep Sleep reset digital core*/
    case 6 : return "SDIO_RESET"; break;             /**<6, Reset by SLC module, reset digital core*/
    case 7 : return "TG0WDT_SYS_RESET"; break;       /**<7, Timer Group0 Watch dog reset digital core*/
    case 8 : return "TG1WDT_SYS_RESET"; break;       /**<8, Timer Group1 Watch dog reset digital core*/
    case 9 : return "RTCWDT_SYS_RESET"; break;       /**<9, RTC Watch dog Reset digital core*/
    case 10 : return "INTRUSION_RESET"; break;       /**<10, Instrusion tested to reset CPU*/
    case 11 : return "TGWDT_CPU_RESET"; break;       /**<11, Time Group reset CPU*/
    case 12 : return "SW_CPU_RESET"; break;          /**<12, Software reset CPU*/
    case 13 : return "RTCWDT_CPU_RESET"; break;      /**<13, RTC Watch dog Reset CPU*/
    case 14 : return "EXT_CPU_RESET"; break;         /**<14, for APP CPU, reseted by PRO CPU*/
    case 15 : return "RTCWDT_BROWN_OUT_RESET"; break;/**<15, Reset when the vdd voltage is not stable*/
    case 16 : return "RTCWDT_RTC_RESET"; break;      /**<16, RTC Watch dog reset digital core and rtc module*/
    default : return "NO_MEAN"; break;
  }
  return "No_Mean";
}

/**
 * @brief Start WebSocket server on port 81
 * 
 * Enables bidirectional real-time communication with clients.
 * Events are processed via the webSocketEvent() callback function.
 * 
 * Sets bit 4 of initSetupState on success.
 */
// Start webSocket
void FrameWeb::startWebSocket() {
  webSocket.begin();
  webSocket.onEvent(webSocketEvent);
  initSetupState = initSetupState | (1<<4);
}

String FrameWeb::simpleUpload() {
  // Build built-in upload page from pre-generated chunks.
  String message = decodeHtmlChunk(HTTP_HEADAL);
   message += decodeHtmlChunk(HTTP_BODYUP);
  return message;
}

String FrameWeb::simpleIndex() {
  // Build built-in tools page and append external custom tools fragment.
  String message = decodeHtmlChunk(HTTP_HEADAL);
  message += decodeHtmlChunk(HTTP_BODYID);
  message += decodeHtmlChunk(HTTP_BODYI0);
  message += externalHtmlTools;
  message += decodeHtmlChunk(HTTP_BODYI1);
  return message;
}

String FrameWeb::simpleFirmware() {
  // Build built-in firmware update page.
  String message = decodeHtmlChunk(HTTP_HEADAL);
  message += decodeHtmlChunk(HTTP_FIRM0);
  return message;
}

String FrameWeb::zipString(const String& input) {
  // Encode plain text to FrameWeb payload format:
  //   <original_size>:<HEX-ENCODED-ZLIB-BYTES>
  // Implementation detail:
  // - Uses low-level tdefl API.
  // - Allocates compressor state on heap to avoid ROM internal MZ_MALLOC path,
  //   which can fail on ESP32-S3 without PSRAM (~164KB compressor structure).
  const size_t sourceLength = input.length();
  const String header = String(static_cast<unsigned long>(sourceLength)) + ":";

  if (sourceLength == 0) {
    return header;
  }

  const int compressFlags = TDEFL_WRITE_ZLIB_HEADER | TDEFL_DEFAULT_MAX_PROBES;
  const size_t outCapacity = sourceLength + (sourceLength / 10) + 256;

  std::unique_ptr<uint8_t[]> outBuf(new (std::nothrow) uint8_t[outCapacity]);
  std::unique_ptr<tdefl_compressor> comp(new (std::nothrow) tdefl_compressor());

  if (!outBuf || !comp) {
    FDBXERR("zipString: allocation failed (heap pressure). freeHeap=%u\n\r", ESP.getFreeHeap());
    return String();
  }

  if (tdefl_init(comp.get(), nullptr, nullptr, compressFlags) != TDEFL_STATUS_OKAY) {
    FDBXERR("zipString: init failed.");
    return String();
  }

  size_t inSize = sourceLength;
  size_t outSize = outCapacity;
  const tdefl_status status = tdefl_compress(comp.get(),
    reinterpret_cast<const void*>(input.c_str()), &inSize,
    outBuf.get(), &outSize,
    TDEFL_FINISH);

  if (status != TDEFL_STATUS_DONE) {
    FDBXERR("zipString: compression failed. status=%s\n\r",String((int)status));
    return String();
  }

  // outSize is remaining free bytes after compression.
  const size_t compressedLength = outCapacity - outSize;
  return header + bytesToHex(outBuf.get(), compressedLength);
}

String FrameWeb::unzipString(const String& input) {
  // Decode FrameWeb payload format:
  //   <original_size>:<HEX-ENCODED-ZLIB-BYTES>
  // Implementation detail:
  // - Uses tinfl_decompress.
  // - Allocates tinfl_decompressor on heap because the ROM helper
  //   tinfl_decompress_mem_to_mem() uses large stack state on ESP32-S3.
  const int separator = input.indexOf(':');
  if (separator < 0) {
    FDBXLN(F("unzipString invalid payload header."));
    return String();
  }

  const String sizeToken = input.substring(0, separator);
  for (size_t i = 0; i < sizeToken.length(); ++i) {
    if (sizeToken[i] < '0' || sizeToken[i] > '9') {
      FDBXLN(F("unzipString invalid size token."));
      return String();
    }
  }

  const size_t expectedLength = static_cast<size_t>(strtoul(sizeToken.c_str(), nullptr, 10));
  const String hexPayload = input.substring(separator + 1);
  if (expectedLength == 0) {
    return hexPayload.length() == 0 ? String("") : String();
  }

  if ((hexPayload.length() % 2) != 0) {
    FDBXLN(F("unzipString invalid hex payload length (must be even)."));
    return String();
  }

  const size_t compressedLength = hexPayload.length() / 2;
  std::unique_ptr<uint8_t[]> compressed(new uint8_t[compressedLength]);
  if (!hexToBytes(hexPayload, compressed.get(), compressedLength)) {
    FDBXLN(F("unzipString invalid hex payload."));
    return String();
  }

  std::unique_ptr<uint8_t[]> output(new uint8_t[expectedLength + 1]);

  // Allocate tinfl_decompressor on heap to avoid stack overflow:
  // tinfl_decompress_mem_to_mem() allocates tinfl_decompressor (~11KB) on the ROM stack,
  // which overflows the loopTask default 8KB stack on ESP32-S3.
  std::unique_ptr<tinfl_decompressor> decomp(new (std::nothrow) tinfl_decompressor());
  if (!decomp) {
    FDBXERR("unzipString: decompressor alloc failed. freeHeap=%u\n\r", ESP.getFreeHeap());
    return String();
  }
  tinfl_init(decomp.get());

  size_t inBufSize = compressedLength;
  size_t outBufSize = expectedLength;
  const tinfl_status tstatus = tinfl_decompress(
    decomp.get(),
    compressed.get(), &inBufSize,
    output.get(), output.get(), &outBufSize,
    TINFL_FLAG_PARSE_ZLIB_HEADER | TINFL_FLAG_USING_NON_WRAPPING_OUTPUT_BUF
  );

  const size_t outputLength = (tstatus == TINFL_STATUS_DONE) ? outBufSize : 0;

  if (outputLength == 0 || outputLength != expectedLength) {
    FDBXLN("unzipString decompression failed. status=" + String((int)tstatus)
      + " inUsed=" + String(inBufSize)
      + " outLen=" + String(outputLength)
      + " expected=" + String(expectedLength));
    return String();
  }

  output[outputLength] = '\0';
  return String(reinterpret_cast<char*>(output.get()));
}

String FrameWeb::decodeHtmlChunk(const char* chunk) {
  // Unified read path for generated HTTP_* chunks.
  // Handles both plain HTML and FrameWeb zip payload transparently.
  // Safety fallback: if payload looks zipped but decode fails, return raw
  // chunk to avoid blank built-in pages.
  const String raw = FPSTR(chunk);
  FDBXLN("decodeHtmlChunk len="+String(raw.length())+" zipped="+String(isZippedString(raw)));
  if (!isZippedString(raw)) {
    return raw;
  }

  const String decoded = unzipString(raw);

  // Keep raw payload when decode fails to avoid returning an empty page fragment.
  return (decoded.length() == 0 && raw != "0:") ? raw : decoded;
}


// Handle Web server ----- used in startWebServer -------------------------------------------------------------------
bool FrameWeb::handleFileRead(String path) {               // send the right file to the client (if it exists)
  FDBXLN("handleFileRead path:" + path);
  if (path.endsWith("/")) path += "index.html";            // If a folder is requested, send the index file
  String contentType = getContentType(path);               // Get the MIME type
  String pathWithGz = path + ".gz";
  if (SPIFFS.exists(pathWithGz) || SPIFFS.exists(path)) {  // If the file exists, either as a compressed archive, or normal
    if (SPIFFS.exists(pathWithGz))                         // If there's a compressed version available
      path += ".gz";                                       // Use the compressed verion
    File file = SPIFFS.open(path, "r");                    // Open the file
    server.streamFile(file, contentType);                  // Send it to the client
    file.close();                                          // Close the file again
    FDBXLN("\tSent file: " + path);
    return true;
  } else {                                                 // Otherwise build answer locally
    if (config.UseToolsLocal) {
      if (path.endsWith("/index.html")){  // Tools                 // For default index.html page after authentification
        if (!server.authenticate(config.LoginName, config.LoginPassword)) {
           server.requestAuthentication();
           return true;
        }
        server.send(200, "text/html", simpleIndex() );     // If not upload.html in FS send light
        return true;
      }
      if (path.endsWith("/update")){                       // return index page which is stored in serverIndex
        if (!server.authenticate(config.LoginName, config.LoginPassword)) {
          server.requestAuthentication();
          return true;
        }
        server.sendHeader("Connection", "close");
        server.send(200, "text/html", simpleFirmware());
        return true;
      }
    }
  }
  FDBXLN("\tFile Not Found: " + path);                  // If the file doesn't exist, return false
  return false;
}

void FrameWeb::handleFileUpload(){                      // upload a new file to the SPIFFS
  HTTPUpload& upload = server.upload();
  String path;
  if(upload.status == UPLOAD_FILE_START){
    path = upload.filename;
    if ( path.length() < 3 ) {
      server.send(500, "text/plain", "Couldn't create file:["+path+"] invalid name.");
      return;
    }
    if(!path.startsWith("/")) path = "/"+path;
    if(!path.endsWith(".gz")) {                          // The file server always prefers a compressed version of a file
      String pathWithGz = path+".gz";                    // So if an uploaded file is not compressed, the existing compressed
      if(SPIFFS.exists(pathWithGz))                      // version of that file must be deleted (if it exists)
         SPIFFS.remove(pathWithGz);
    }
    FDBXMF("handleFileUpload Name: %s\n\r", path.c_str());
    fsUploadFile = SPIFFS.open(path, "w");               // Open the file for writing in SPIFFS (create if it doesn't exist)
    path = String();
  } else if(upload.status == UPLOAD_FILE_WRITE){
    if(fsUploadFile)
      fsUploadFile.write(upload.buf, upload.currentSize); // Write the received bytes to the file
  } else if(upload.status == UPLOAD_FILE_END){
    if(fsUploadFile) {                                    // If the file was successfully created
      fsUploadFile.close();                               // Close the file again
      FDBXMF("handleFileUpload Size: %d\n\r", upload.totalSize);
      server.sendHeader("Location","/success.html");      // Redirect the client to the success page
      server.send(303);
    } else {
      server.send(500, "text/plain", "Couldn't upload file:["+path+"] in SPIFFS.");
    }
  }
}

String FrameWeb::textNotFound(){
  String message = "File Not Found\n\r";
  message += "URI: ";
  message += server.uri();
  message += " Method: ";
  message += (server.method() == HTTP_GET)?"GET":"POST";
  message += " Arguments: ";
  message += server.args();
  message += "\n\r";
  for (uint8_t i=0; i<server.args(); i++)
    message += " " + server.argName(i) + ": " + server.arg(i) + ",";
  message += "\n\r";
  return message;
}

void FrameWeb::handlePost() {
  if (server.arg("cmd")!="") {
      if (!server.authenticate(config.LoginName, config.LoginPassword)) {
        server.requestAuthentication();
        return;
      }
      FDBXMF("cmd=%s\n\r", server.arg("cmd").c_str());
      if (server.arg("cmd") == "save-config" ) saveConfiguration(filename, config);
      if (server.arg("cmd") == "reset-wifi" ) ResetWifi = true;
      if (server.arg("cmd") == "restart" ) RebootAsap = true;
      if (server.arg("cmd") == "restore" ) RestoreAsap = true;
  }
  server.sendHeader("Location","/");      // Redirect the client to the index page
  server.send(303);
  return;
}

void FrameWeb::handleNotFound(){ // if the requested file or page doesn't exist, return a 404 not found error
  if(!handleFileRead(server.uri())){          // check if the file exists in the flash memory (SPIFFS), if so, send it
    server.send(404, "text/plain", textNotFound());
  }
}

//  Directory list
void FrameWeb::explorer(String& ret, fs::FS &fs, const char * dirname, uint8_t levels) {
  File root = fs.open(dirname);
  if (!root) {  return;  }
  if (!root.isDirectory()) { return; }
  File file = root.openNextFile();
  // For each file in the directory, add an entry to the HTML list with file name, size, and action buttons
  while (file) {
    if (file.isDirectory()) {
      if (levels)  explorer(ret, fs, file.name(), levels - 1);
    } else {
      String strf = (file.name());
      String filelist = FPSTR(HTTP_EXPL1);
      filelist.replace("##F##", strf);
      filelist.replace("##S##",  formatBytes(file.size()) );
      ret += filelist;
    }
    file = root.openNextFile();
  }
  return;
}

void FrameWeb::download(String filename) {
  File download = SPIFFS.open(filename);
  if (download) {
    server.sendHeader("Content-Type", "text/text");
    server.sendHeader("Content-Disposition", "attachment; filename="+filename);
    server.sendHeader("Connection", "close");
    server.streamFile(download, "application/octet-stream");
    download.close();
    return;
  }
  server.send(500, "text/plain", F("500: couldn't download file"));
}

void FrameWeb::sendLs() {
  String ls;
  listDir(ls, SPIFFS, "/", 0);
  server.send(200, "text/plain", ls);
}

void FrameWeb::upload_get() {
  if (!server.authenticate(config.LoginName, config.LoginPassword)) {
    server.requestAuthentication();
    return;
  }
  if (!handleFileRead("/upload.html")) {    // upload.html exist on FS
    if (config.UseToolsLocal) {
      server.send(200, "text/html", simpleUpload() ); // If not upload.html in FS send lightweight
      return;
    }
    else {
      server.send(404, "text/plain", "FileNotFound");
      return;
    }
  }
}

void FrameWeb::upload_post() {
  server.send(200, "text/plain", "");
}

void FrameWeb::exploreWeb() {
#ifdef LOG_FRAMEWEB_ENABLED
  showAH();
#endif
  if (!server.authenticate(config.LoginName, config.LoginPassword)) 
    return server.requestAuthentication();
  if (server.arg("cmd")=="remove") { 
    if (server.arg("file") != "" ) SPIFFS.remove("/"+server.arg("file"));
  }
  if (server.arg("cmd")=="download") {
    if (server.arg("file") != "" ) download("/"+server.arg("file"));
  }
  // Return list of files in table
  String msg = decodeHtmlChunk(HTTP_HEADAL);
  msg += decodeHtmlChunk(HTTP_EXPL0);

  // old
  //String msg = FPSTR(HTTP_HEADAL);
  //msg += FPSTR(HTTP_EXPL0);
  
  explorer(msg, SPIFFS, "/", 0);
  msg += F("</div></div><div style='text-align: center; margin-top: 20px;'><button onclick=\"window.location='/';\">Back</button></div></div></body></html>");
  server.send(200, "text/html", msg);
}

void FrameWeb::update() {
  server.sendHeader("Connection", "close");
  server.send(200, "text/plain", (Update.hasError())?"FAIL":"OK");
  ESP.restart();
}

void FrameWeb::update2() {
  HTTPUpload& upload = server.upload();
  if(upload.status == UPLOAD_FILE_START){
    FDBXMF("Update: %s\n\r", upload.filename.c_str());
    if(!Update.begin(UPDATE_SIZE_UNKNOWN)){ //start with max available size
      Update.printError(Serial);
    }
  } else if(upload.status == UPLOAD_FILE_WRITE){
    /* flashing firmware to ESP*/
    if(Update.write(upload.buf, upload.currentSize) != upload.currentSize){
      Update.printError(Serial);
    }
  } else if(upload.status == UPLOAD_FILE_END){
    if(Update.end(true)){ //true to set the size to the current progress
      FDBXMF("Update Success: %u\n\rRebooting...\n\r", upload.totalSize);
    } else {
      Update.printError(Serial);
    }
  }
}

// Start web server -------------------------------------------------------------------
void FrameWeb::startWebServer(){

  // POST
  server.on("/post",  HTTP_POST, []() {        // If a POST request is sent to the /edit.html address,
     myFrameWeb->handlePost();
  });

  // Simple command wihout pwd
  server.on("/ls", [](){                      // Get list of file in FS
    myFrameWeb->sendLs();
  });

  /* handling uploading firmware file */
  server.on("/update", HTTP_POST, [](){
    myFrameWeb->update();
  },[](){
    myFrameWeb->update2();
  });

  // handling upload file
  server.on("/upload", HTTP_GET, []() {        // Upload
    myFrameWeb->upload_get();
  });

  server.on("/upload", HTTP_POST, []() {       // Back after selection
    myFrameWeb->upload_post();
    },[](){
     myFrameWeb->handleFileUpload();
    });

  server.onNotFound([]() {
    myFrameWeb->handleNotFound();
  });

  server.on("/explorer", [](){                  // Get list of file in FS
    myFrameWeb->exploreWeb();
  });

  server.begin();
  initSetupState = initSetupState | (1<<5);
}

// Start MDNS
void FrameWeb::startMDNS() {
  // - first argument is the domain name, in this example   the fully-qualified domain name is "esp32.local"
  // - second argument is the IP address to advertise   we send our IP address on the WiFi network
  if (!MDNS.begin(config.HostName))
    FDBXLN(F("Error setting up MDNS responder!"));
  FDBXMF("mDNS responder started: %s\n\r", config.HostName);
  MDNS.addService("http",  "tcp", 80);
  MDNS.addService("ws",    "tcp", 81);
  MDNS.addService("esp32", "tcp", 8888); // Announce esp32 service port 8888 TCP
  initSetupState = initSetupState | (1<<6);
}

// Arduino core -------------------------------------------------------------
void FrameWeb::setup( /*void (*func)(WiFiManager* myWiFiManager),*/ const char* hostname) {
  FDBXMF("FrameWeb::setup started version: %s\n\r", FrameVersion);
  startSPIFFS();                   // Start FS (list all contents)
  loadConfiguration(filename, config, hostname); // Read config file
  startWifiManager();              // Start a Wi-Fi access point, and try to connect
  startOTA();                      // Start the OTA service
  startWebSocket();                // Start a WebSocket server
  startWebServer();                // Start a HTTP server with a file read handler and an upload handler
  startMDNS();                     // Start the mDNS responder  //DBXLN(FPSTR(FrameVersion));
  FDBXMF("FrameWeb::setup ready  IP: %s\n\r", WiFi.localIP().toString().c_str());
  FDBXMF("FrameWeb::setup ready MAC: %s\n\r", WiFi.macAddress().c_str() );
  
}

void FrameWeb::loop() {
  
  server.handleClient();         // constantly check for events
  webSocket.loop();              // constantly check for websocket events
  ArduinoOTA.handle();           // listen for OTA events
  if (ResetWifi) {
    wifiManager.resetSettings(); // BUG the stored ssid no cleared !!
    wifi_init_config_t cfg = WIFI_INIT_CONFIG_DEFAULT(); //load the flash-saved configs
    esp_wifi_init(&cfg); //initiate and allocate wifi resources (does not matter if connection fails)
    delay(2000); //wait a little bit
    if(esp_wifi_restore() != ESP_OK) {
      FDBXLN("WiFi is not initialized by esp_wifi_init");
    } else {
      /* It appears that the code provided is not valid C++ code. The text "FDBXLN" and " */
      FDBXLN("WiFi Configurations Cleared!");
    }
    wifiManager.startConfigPortal(config.HostName, NULL);
    ESP.restart();
  }
  if (RebootAsap) { 
    ESP.restart(); // Restart in case of error
  }
  if (RestoreAsap) {             // Reset to factory settings
    FDBXLN(F("Format SPIFS..."));
    SPIFFS.format();
    wifiManager.resetSettings(); // BUG the stored ssid no cleared !!
    ESP.restart();
  }
}